// 2018dsep1.js
// 直接用 .push 追加題目，不會覆蓋之前的數據

questions.push(
    {
        id: "2018-DSE-MATH-CP1-Q01",
        year: 2018,
        type: "P1",
        section: "A1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Change of Subject"],
        difficulty: 1,
        content: `令 $b$ 成為公式 $\\dfrac{a+4}{3}=\\dfrac{b+1}{2}$ 的主項。<span class="marks">(3分)</span>`,
        hint: `交叉相乘後解出 $b$。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q02",
        year: 2018,
        type: "P1",
        section: "A1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Laws of Indices"],
        difficulty: 1,
        content: `化簡 $\\dfrac{xy^7}{(x^2 y^3)^4}$，並以正指數表示答案。<span class="marks">(3分)</span>`,
        hint: `先展開分母的指數，再應用指數定律。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q03",
        year: 2018,
        type: "P1",
        section: "A1",
        level: ["Junior"],
        domain: ["Number and Cardinality"],
        topic: ["Approximation and Errors"],
        difficulty: 1,
        content: `<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">將 $265.473$ 上捨入至最接近的整數。<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">將 $265.473$ 下捨入至一位小數。<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(c)</span><div class="q-text-content">將 $265.473$ 捨入至二位有效數字。<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `分別應用上捨入、下捨入及有效數字規則。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q04",
        year: 2018,
        type: "P1",
        section: "A1",
        level: ["Junior"],
        domain: ["Data Handling"],
        topic: ["Probability"],
        difficulty: 1,
        content: `某盒子中有 $n$ 個白球、$5$ 個黑球及 $8$ 個紅球。若從該盒子中隨機抽出一個球，則抽出紅球的概率為 $\\dfrac{2}{5}$。求 $n$ 的值。<span class="marks">(3分)</span>`,
        hint: `列出紅球概率方程求解 $n$。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q05",
        year: 2018,
        type: "P1",
        section: "A1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Factorization"],
        difficulty: 1,
        content: `因式分解<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">$9r^3 - 18r^2 s$，<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">$9r^3 - 18r^2 s - rs^2 + 2s^3$。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 提取公因式。<br>(b) 分組因式分解。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q06",
        year: 2018,
        type: "P1",
        section: "A1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Linear Inequalities and Compound Inequalities"],
        difficulty: 2,
        content: `<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求同時滿足 $\\dfrac{3-x}{2} > 2x+7$ 及 $x+8 \\ge 0$ 的 $x$ 值的範圍。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">寫出同時滿足 (a) 的不等式的最大整數。<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 分別解兩個不等式後取交集。<br>(b) 從範圍中取最大整數。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q07",
        year: 2018,
        type: "P1",
        section: "A1",
        level: ["Junior"],
        domain: ["Number and Cardinality"],
        topic: ["Percentages"],
        difficulty: 2,
        content: `某花瓶的標價較其成本高 $30\\%$。該花瓶以其標價六折售出並虧蝕 $\$88$。求該花瓶的標價。<span class="marks">(5分)</span>`,
        hint: `設成本為 $x$，列出標價與售價關係後求解。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q08",
        year: 2018,
        type: "P1",
        section: "A1",
        level: ["Junior"],
        domain: ["Geometry"],
        topic: ["Geometry (Circles)"],
        difficulty: 2,
        content: `圖1中，$ABCDE$ 為一圓。已知 $AB \\parallel ED$。$AD$ 與 $BE$ 相交於點 $F$。<br>以 $\\theta$ 表 $x$ 及 $y$。<span class="marks">(5分)</span>`,
        hint: `利用平行線性質、圓周角及對頂角。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q09",
        year: 2018,
        type: "P1",
        section: "A1",
        level: ["Junior"],
        domain: ["Number and Cardinality"],
        topic: ["Rates, Ratios and Proportions"],
        difficulty: 2,
        content: `某汽車以平均速率 $72$ km/h 由 $P$ 城駛至 $Q$ 城，該汽車然後以平均速率 $90$ km/h 由 $Q$ 城駛至 $R$ 城。已知該汽車在整段行程中以 $161$ 分鐘行駛 $210$ km。該汽車由 $P$ 城駛至 $Q$ 城需時多久？<span class="marks">(5分)</span>`,
        hint: `設 $PQ$ 距離為 $d$，列出時間方程求解。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q10",
        year: 2018,
        type: "P1",
        section: "A2",
        level: ["Senior"],
        domain: ["Data Handling"],
        topic: ["Measures of Dispersion"],
        difficulty: 2,
        content: `下面的框線圖顯示某公司 $X$ 組文員的年歲的分佈。已知這分佈的分佈域及四分位數間距分別為 $43$ 及 $21$。<br>（框線圖標示：$19$、$27$、$38$、$a$、$b$）<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $a$ 及 $b$。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">該公司 $Y$ 組有五名文員且其中三名的年歲均為 $38$。已知 $Y$ 組文員的年歲的分佈域為 $20$。$X$ 組與 $Y$ 組現合併為一部門。公司經理宣稱該部門文員的年歲的分佈域與 $X$ 組文員的年歲的分佈域必為相同。你是否同意？試解釋你的答案。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 由分佈域及 IQR 求 $a$、$b$。<br>(b) 考慮合併後最大/最小值可能改變。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q11",
        year: 2018,
        type: "P1",
        section: "A2",
        level: ["Senior"],
        domain: ["Data Handling"],
        topic: ["Measures of Central Tendency"],
        difficulty: 2,
        content: `下表顯示一些家庭的子女人數的分佈：<br><table class="q-table"><tr><th>子女人數</th><th>0</th><th>1</th><th>2</th><th>3</th><th>4</th></tr><tr><th>家庭數目</th><td>$k$</td><td>2</td><td>9</td><td>6</td><td>7</td></tr></table><br>已知 $k$ 為一正整數。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">若該分佈的眾數為 $2$，寫出<br><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">$k$ 的最小可取值；</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">$k$ 的最大可取值。<br><span class="marks">(2分)</span><div class="q-clearfix"></div></div></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">若該分佈的中位數為 $2$，寫出<br><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">$k$ 的最小可取值；</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">$k$ 的最大可取值。<br><span class="marks">(2分)</span><div class="q-clearfix"></div></div></div></div></div><div class="q-line"><span class="q-label">(c)</span><div class="q-text-content">若該分佈的平均值為 $2$，求 $k$ 的值。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 眾數為 2 的條件限制 $k$ 的範圍。<br>(b) 中位數位置決定 $k$ 範圍。<br>(c) 由平均值方程求 $k$。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q12",
        year: 2018,
        type: "P1",
        section: "A2",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Polynomials", "Remainder Theorem and Factor Theorem"],
        difficulty: 3,
        content: `設 $f(x) = 4x(x+1)^2 + ax + b$，其中 $a$ 及 $b$ 均為常數。已知 $x-3$ 為 $f(x)$ 的因式。當 $f(x)$ 除以 $x+2$ 時，餘數為 $2b+165$。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $a$ 及 $b$。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">某人宣稱方程 $f(x)=0$ 有至少一個無理根。你是否同意？試解釋你的答案。<span class="marks">(4分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 利用因式定理及餘數定理求 $a$、$b$。<br>(b) 因式分解後判斷根的性質。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q13",
        year: 2018,
        type: "P1",
        section: "A2",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Geometry (Triangles)", "Pythagoras Theorem"],
        difficulty: 3,
        content: `圖 2 中，$ABCD$ 為一梯形，且 $\\angle ABC = 90^\\circ$ 及 $AB \\parallel DC$。$E$ 為 $BC$ 上的一點使得 $\\angle AED = 90^\\circ$。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">證明 $\\triangle ABE \\sim \\triangle ECD$。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">已知 $AB = 15$ cm、$AE = 25$ cm 及 $CE = 36$ cm。<br><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">求 $CD$ 的長度。</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">求 $\\triangle ADE$ 的面積。</div></div><div class="q-line q-level-2"><span class="q-label">(iii)</span><div class="q-text-content">$AD$ 上是否有一點 $F$ 使得 $E$ 與 $F$ 間的距離少於 $23$ cm？試解釋你的答案。<br><span class="marks">(6分)</span><div class="q-clearfix"></div></div></div></div></div>`,
        hint: `(a) 利用平行線及直角證明 AA 相似。<br>(b) 用相似比及畢氏定理計算。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q14",
        year: 2018,
        type: "P1",
        section: "A2",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Mensuration"],
        difficulty: 3,
        content: `一底半徑為 $8$ cm 及高為 $64$ cm 的直立圓柱形的容器與一底半徑為 $20$ cm 及高為 $60$ cm 的倒置直立圓錐形的器皿均鉛垂放置。該容器載滿了水。現將該容器內的水倒入該器皿內。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求該器皿內水的體積，答案以 $\\pi$ 表示。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">求該器皿內水的深度。<span class="marks">(4分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(c)</span><div class="q-text-content">若將一半徑為 $14$ cm 的實心金屬球體隨後放進該器皿內，且該球體完全浸入水中，水會否溢出？試解釋你的答案。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 圓柱體積即水體積。<br>(b) 用相似圓錐求深度。<br>(c) 比較球體積與剩餘空間。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q15",
        year: 2018,
        type: "P1",
        section: "B",
        level: ["Senior"],
        domain: ["Data Handling"],
        topic: ["Permutations and Combinations"],
        difficulty: 1,
        content: `一個八位電話號碼由 $2$、$3$、$4$、$5$、$6$、$7$、$8$ 及 $9$ 的排列所組成。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">可組成多少個不同的八位電話號碼？<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">若八位電話號碼的第一個位及最後一個位均為奇數，則可組成多少個不同的八位電話號碼？<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 全排列。<br>(b) 先選首尾奇數再排列中間。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q16",
        year: 2018,
        type: "P1",
        section: "B",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Sequences"],
        difficulty: 2,
        content: `某等比數列的第 $3$ 項及第 $4$ 項分別為 $720$ 及 $864$。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求該數列的第 $1$ 項。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">求 $n$ 的最大值使得第 $(n+1)$ 項與第 $(2n+1)$ 項之和小於 $5 \\times 10^4$。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 由公比求首項。<br>(b) 列出不等式後求最大整數 $n$。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q17",
        year: 2018,
        type: "P1",
        section: "B",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Trigonometry (2D)", "Trigonometry (3D)"],
        difficulty: 3,
        content: `<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">圖 3(a) 中，$ABCD$ 為一紙卡，其形狀為平行四邊形。已知 $AB = 60$ cm、$\\angle ABD = 20^\\circ$ 及 $\\angle BAD = 120^\\circ$。<br>求 $AD$ 的長度。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">將圖 3(a) 中的紙卡沿 $BD$ 摺起，使得 $A$ 與 $C$ 間的距離為 $40$ cm（見圖 3(b)）。<br><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">求 $\\angle ABC$。</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">求平面 $ABD$ 與平面 $BCD$ 間的交角。<br><span class="marks">(5分)</span><div class="q-clearfix"></div></div></div></div></div>`,
        hint: `(a) 用正弦公式。<br>(b) 用餘弦公式求角，再求二面角。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q18",
        year: 2018,
        type: "P1",
        section: "B",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Variations", "Functions and Graphs"],
        difficulty: 3,
        content: `已知 $f(x)$ 的一部分隨 $x^2$ 正變，而另一部分則隨 $x$ 正變。假定 $f(2)=60$ 及 $f(3)=99$。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $f(x)$。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">設 $Q$ 為 $y=f(x)$ 的圖像的頂點及 $R$ 為 $y=27-f(x)$ 的圖像的頂點。<br><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">利用配方法，求 $Q$ 的坐標。</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">寫出 $R$ 的坐標。</div></div><div class="q-line q-level-2"><span class="q-label">(iii)</span><div class="q-text-content">點 $S$ 的坐標為 $(56,0)$。設 $P$ 為 $\\triangle QRS$ 的外心。描述 $P$、$Q$ 與 $R$ 之間的幾何關係。試解釋你的答案。<br><span class="marks">(5分)</span><div class="q-clearfix"></div></div></div></div></div>`,
        hint: `(a) 設 $f(x)=Ax^2+Bx$，代入求 $A$、$B$。<br>(b) 配方找頂點，再分析外心位置。`,
        solution: ``
    },
    {
        id: "2018-DSE-MATH-CP1-Q19",
        year: 2018,
        type: "P1",
        section: "B",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Equations of Circles", "Intersection of Straight Line and Circle"],
        difficulty: 3,
        content: `圓 $C$ 的圓心的坐標為 $(8,2)$。將 $C$ 的半徑記為 $r$。設 $L$ 為直線 $kx-5y-21=0$，其中 $k$ 為一常數。已知 $L$ 為 $C$ 的切線。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $C$ 的方程，答案以 $r$ 表示。由此，以 $k$ 表 $r^2$。<span class="marks">(4分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">$L$ 通過點 $D(18,39)$。<br><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">求 $r$。</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">已知 $L$ 與 $y$ 軸相交於點 $E$。設 $F$ 為一點使得 $C$ 為 $\\triangle DEF$ 的內切圓。$\\triangle DEF$ 是否一鈍角三角形？試解釋你的答案。<br><span class="marks">(8分)</span><div class="q-clearfix"></div></div></div></div></div>`,
        hint: `(a) 用圓心到直線距離等於半徑求關係。<br>(b) 代入點求 $k$ 及 $r$，再分析三角形性質。`,
        solution: ``
    }
);
