// 2022dsep1.js
// 嚴格遵照原始擷取文字（包含所有斷句、標點、漏字與原有排版），生成完整 js 檔

questions.push(
    {
        id: "2022-DSE-MATH-CP1-Q01",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Laws of Indices"],
        difficulty: 1,
        content: `1.<br>化簡<br>$\\frac{(a^{3}b^{-2})^{4}}{a^{-5}b^{6}}$ ,並以正指數表示答案。<br>(3分)`,
        hint: `先利用指數定律 $(m^k)^n = m^{kn}$ 展開分子，再利用 $\\dfrac{x^p}{x^q} = x^{p-q}$ 化簡相同底數的項。`,
        solution: `$\\dfrac{(a^{3}b^{-2})^{4}}{a^{-5}b^{6}} = \\dfrac{a^{12}b^{-8}}{a^{-5}b^{6}} = \\dfrac{a^{12-(-5)}}{b^{6-(-8)}} = \\dfrac{a^{17}}{b^{14}}$`
    },
    {
        id: "2022-DSE-MATH-CP1-Q02",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Linear Equations"],
        difficulty: 1,
        content: `2.<br>設x及y為兩數。x與y之和為456而7與x之積為y。求x。<br>(3分)`,
        hint: `根據題目條件列出聯立方程 $x+y=456$ 及 $7x=y$，然後利用代入法求解。`,
        solution: `已知 $x + y = 456$ 及 $7x = y$。<br>將 $y = 7x$ 代入第一式：<br>$x + 7x = 456$<br>$8x = 456$<br>$x = 57$`
    },
    {
        id: "2022-DSE-MATH-CP1-Q03",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Algebraic Fractions"],
        difficulty: 1,
        content: `3. 化簡 $\\frac{3}{k-9}+\\frac{2}{5k+6}\\cdot$<br>(3分)`,
        hint: `先尋找通分母 $(k-9)(5k+6)$，然後將分子展開並合併同類項。`,
        solution: `$\\dfrac{3}{k-9}+\\dfrac{2}{5k+6} = \\dfrac{3(5k+6)+2(k-9)}{(k-9)(5k+6)} = \\dfrac{15k+18+2k-18}{(k-9)(5k+6)} = \\dfrac{17k}{(k-9)(5k+6)}$`
    },
    {
        id: "2022-DSE-MATH-CP1-Q04",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Factorization"],
        difficulty: 2,
        content: `4.<br>因式分解<br>(a)<br>9c2-6c+1,<br>(b)<br>$(4c+d)^{2}-9c^{2}+6c-1$<br>(4分)`,
        hint: `(a) 利用完全平方公式 $x^2-2xy+y^2=(x-y)^2$。<br>(b) 先分組抽取負號，利用 (a) 的結果，再應用平方差公式 $x^2-y^2=(x+y)(x-y)$。`,
        solution: `<span class=\"q-label\">(a)</span> $9c^{2}-6c+1 = (3c-1)^{2}$<br><br><span class=\"q-label\">(b)</span> $(4c+d)^{2}-9c^{2}+6c-1 = (4c+d)^{2}-(9c^{2}-6c+1) = (4c+d)^{2}-(3c-1)^{2} = (4c+d+3c-1)[4c+d-(3c-1)] = (7c+d-1)(c+d+1)$`
    },
    {
        id: "2022-DSE-MATH-CP1-Q05",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Arithmetic"],
        topic: ["Percentages"],
        difficulty: 2,
        content: `5.<br>某風扇以其標價七折售出。售出該風扇後,盈利為 \\$78 且盈利百分率為26%。<br>求該風扇的標價。<br>(4分)`,
        hint: `盈利 = 成本 $\\times$ 盈利百分率，由此可求出成本，進而得到售價。再利用「標價 $\\times 70\\% =$ 售價」求出標價。`,
        solution: `設 \$x 為該風扇的成本。<br>$26\\%x = 78 \\Rightarrow x = 300$<br>售價 = $300 + 78 = \\$378$<br>設 \$y 為該風扇的標價。<br>$70\\%y = 378 \\Rightarrow y = 540$<br>因此，該風扇的標價為 \\$540。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q06",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Inequalities"],
        difficulty: 2,
        content: `6.<br>考慮複合不等式<br>-2(3x+2)>x+10或2x≤-8<br>(a)<br>解<br>(*1)。<br>(b)<br>寫出滿足(*)的最大整數。<br>(4分)`,
        hint: `(a) 分別解出兩個不等式，注意「或 (or)」代表取兩個解區域的聯集。<br>(b) 在解區域中找出數值最大的整數。`,
        solution: `<span class=\"q-label\">(a)</span> 對於第一個不等式：$-6x-4 > x+10 \\Rightarrow -7x > 14 \\Rightarrow x < -2$<br>對於第二個不等式：$2x \\le -8 \\Rightarrow x \\le -4$<br>由於是「或」的關係，組合兩者後，該複合不等式的解為 $x < -2$。<br><br><span class=\"q-label\">(b)</span> 滿足 $x < -2$ 的最大整數為 $-3$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q07",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Geometry"],
        topic: ["Coordinate Geometry"],
        difficulty: 2,
        content: `7.<br>點S及點T的坐標分別為(12,-5)及(-3,-7)。S繞O逆時針方向旋轉90°至S',<br>其中為原點。T'為T對x軸的反射影像。<br>(a)<br>寫出S 及T'的坐標。<br>(b)<br>求S'T'的斜率。<br>(4分)`,
        hint: `(a) 點 $(x, y)$ 繞原點逆時針旋轉 $90^{\\circ}$ 後變為 $(-y, x)$；對 $x$ 軸反射後變為 $(x, -y)$。<br>(b) 使用斜率公式 $m = \\dfrac{y_2-y_1}{x_2-x_1}$。`,
        solution: `<span class=\"q-label\">(a)</span> $S'$ 的坐標為 $(5, 12)$； $T'$ 的坐標為 $(-3, 7)$。<br><br><span class=\"q-label\">(b)</span> 直線 $S'T'$ 的斜率 $= \\dfrac{12-7}{5-(-3)} = \\dfrac{5}{8}$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q08",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Geometry"],
        topic: ["Geometric Proofs"],
        difficulty: 2,
        content: `8.<br>圖1中,A 是位於四邊形<br>已知 ∠ABC=∠AED 及AB = AE.<br>BCDE 以內的一點使得 AC // ED 及AD // BC<br>圖1<br>(a) 證明 $\\Delta ABC\\cong\\Delta AED$。<br>(b) 若 $\\angle ABC=39^{\\circ}$ 及∠DAE=87°,求∠ACD。<br>(5分)`,
        hint: `(a) 利用平行線的內錯角相等找出力等角，再以 AAS 證明全等。<br>(b) 利用全等三角形對應角相等及等腰三角形性質求解。`,
        solution: `<span class=\"q-label\">(a)</span> $\\angle ACB = \\angle CAD$ （$AD \\parallel BC$ 的內錯角）<br>$\\angle CAD = \\angle ADE$ （$AC \\parallel ED$ 的內錯角）<br>所以 $\\angle ACB = \\angle ADE$<br>又 $\\angle ABC = \\angle AED$ （已知）且 $AB = AE$ （已知）<br>因此，$\\triangle ABC \\cong \\triangle AED$ （AAS）<br><br><span class=\"q-label\">(b)</span> $\\angle BAC = \\angle DAE = 87^{\\circ}$ （全等三角形的對應角）<br>在 $\\triangle ABC$ 中，$\\angle ACB = 180^{\\circ} - 87^{\\circ} - 39^{\\circ} = 54^{\\circ}$<br>$\\angle CAD = \\angle ACB = 54^{\\circ}$ （內錯角）<br>因為 $\\triangle ABC \\cong \\triangle AED$，所以 $AC = AD$（對應邊）<br>在等腰 $\\triangle ACD$ 中，$\\angle ACD = \\angle ADC = \\dfrac{180^{\\circ}-54^{\\circ}}{2} = 63^{\\circ}$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q09",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Data Handling"],
        topic: ["Statistical Charts"],
        difficulty: 2,
        content: `9.<br>下面的頻數分佈表及累積頻數分佈表均顯示某群學生完成某<br>分佈。<br>3km 賽跑所需時間的<br>The following table:<br>"所需時間(分鐘)","頻數"<br>"10-14","a"<br>"15-19","9"<br>"20-24","b"<br>"25-29","3"<br>The following table:<br>"所需時間少於(分鐘)","累積頻數"<br>"14.5","3"<br>"19.5","X"<br>"24.5","y"<br>"29.5","20"<br>(a) 寫出x的值。<br>(b) 求該分佈的平均值。<br>(c) 求從該群中隨機選出的一名學生完成該 3km 賽跑所需時間少於19.5 分鐘的<br>概率。<br>(5分)`,
        hint: `(a) 對比兩個表，少於 14.5 的頻數就是第一組的頻數 a。而少於 19.5 的累積頻數等於前兩組頻數之和。<br>(b) 利用各組組中點與頻數加權求平均值。<br>(c) 概率 = 滿足條件的人數 / 總人數。`,
        solution: `<span class=\"q-label\">(a)</span> 由表可知 $a = 3$。所以 $X = a + 9 = 3 + 9 = 12$。且總人數為 20，可得 $b = 20 - 3 - 9 - 3 = 5$。<br><br><span class=\"q-label\">(b)</span> 各組組中點分別為 12、17、22、27。<br>平均值 $= \\dfrac{12(3) + 17(9) + 22(5) + 27(3)}{20} = \\dfrac{380}{20} = 19\\text{ 分鐘}$<br><br><span class=\"q-label\">(c)</span> 所求的概率 $= \\dfrac{X}{20} = \\dfrac{12}{20} = \\dfrac{3}{5}$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q10",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Variations"],
        difficulty: 3,
        content: `10. 已知 f(x)<br>的一部分隨 x² 正變,而另一部分則隨 x正變。假定 $f(4)=96$<br>及 $f(-5)=15$.<br>(a) 求f(x)。<br>(3分)<br>(b)<br>寫出 $y=8f(x)$ 的圖像的x截距。<br>(1分)<br>(c)<br>設為一實常數。求k值的範圍使得方程 $f(x)=k$ 有兩個相異的實根。(2分)`,
        hint: `(a) 設 $f(x) = ax^2 + bx$，代入已知值解聯立方程。<br>(b) 圖像的 $x$ 截距即為令 $y=0$（即 $f(x)=0$）時 $x$ 的值。<br>(c) 方程有兩相異實根，代表其判別式 $\\Delta > 0$。`,
        solution: `<span class=\"q-label\">(a)</span> 設 $f(x) = ax^2 + bx$<br>代入已知條件：<br>$a(4)^2 + b(4) = 96 \\Rightarrow 16a + 4b = 96$<br>$a(-5)^2 + b(-5) = 15 \\Rightarrow 25a - 5b = 15$<br>解聯立方程得 $a = 3, b = 12$。<br>因此，$f(x) = 3x^2 + 12x$。<br><br><span class=\"q-label\">(b)</span> 令 $8f(x) = 0 \\Rightarrow 8(3x^2 + 12x) = 0 \\Rightarrow 24x(x + 4) = 0$。<br>所以 $x$ 截距為 $0$ 及 $-4$。<br><br><span class=\"q-label\">(c)</span> 方程為 $3x^2 + 12x - k = 0$。<br>因為有兩個相異實根，$\\Delta > 0$<br>$(12)^2 - 4(3)(-k) > 0$<br>144 + 12k > 0 \\Rightarrow k > -12$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q11",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Data Handling"],
        topic: ["Measures of Dispersion"],
        difficulty: 3,
        content: `11. 下面的幹葉圖顯示某足球隊球員的年齡的分佈。<br>幹(十位) 葉(個位)<br>1 7 8 9<br>20<br>a<br>a<br>889<br>3 bb 5 5 6 6 6 6 7 8<br>43<br>該分佈的四分位數間距及中位數分別為14及31。<br>(a) 求a及b。<br>(3分)<br>(b)<br>某球員現退出該足球隊。<br>(i) 該分佈的眾數有否因該球員退出而改變?試解釋你的答案。<br>(ii) 若該分佈的分佈域減小,求該分佈的最大可取標準差。<br>(4分)`,
        hint: `(a) 利用中位數為 31 與四分位數間距為 14 建立方程組求解 a 和 b。<br>(b)(i) 找出原本的眾數，看刪除特定的數後是否改變。<br>(b)(ii) 分別考慮最大值或最小值被移去的情形以使分佈域減小，比較找出最大可能標準差。`,
        solution: `<span class=\"q-label\">(a)</span> 根據中位數為 $31$，可知 $30+b = 31 \\Rightarrow b = 1$。<br>已知總人數為 21 人，利用四分位數間距公式：$Q_3 - Q_1 = 14$，經計算可得 $a = 2$。<br><br><span class=\"q-label\">(b)(i)</span> 原眾數為 $36$。不論哪位球員退出，該分佈的眾數均沒有改變。<br><br><span class=\"q-label\">(b)(ii)</span> 考慮使分佈域減小的兩種情況（移去最小的 17 歲或最大的 43 歲）：<br>情況1：17 歲球員退出，標準差 $\\approx 7.16$<br>情況2：43 歲球員退出，標準差 $\\approx 7.13$<br>因此，最大可取標準差為 $7.16$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q12",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Equations of Circles"],
        difficulty: 4,
        content: `12.<br>(3分)<br>圓C的方程為 $x^{2}+y^{2}$-154x-128y+224=0。將C的圓心記為G。點H的坐標<br>為(65,48)。<br>(a)<br>求G與H間的距離。<br>(b)<br>設P為C上的一動點。當 GHP的面積最大時,<br>(i) 描述 GH與GP 之間的幾何關係;<br>(ii) 求AGHP的周界。<br>(4分)`,
        hint: `(a) 圓心坐標為 $(77, 64)$，再利用兩點距離公式求 $GH$。<br>(b)(i) 當 $\\triangle GHP$ 的面積最大時，以 $GH$ 為底，高 $GP$（即半徑）必須垂直於底，故 $GH \\perp GP$。<br>(b)(ii) 使用畢氏定理求出 $HP$，周界 $= GH + GP + HP$。`,
        solution: `<span class=\"q-label\">(a)</span> 圓心 $G$ 的坐標為 $(77, 64)$。<br>$G$ 與 $H$ 間的距離 $= \\sqrt{(77-65)^{2}+(64-48)^{2}} = 20$。<br><br><span class=\"q-label\">(b)(i)</span> 當 $\\triangle GHP$ 的面積最大時，$GH$ 與 $GP$ 互相垂直（即 $GH \\perp GP$）。<br><br><span class=\"q-label\">(b)(ii)</span> 圓 $C$ 的半徑 $GP = \\sqrt{77^2+64^2-224} = 99$。<br>由於 $GH \\perp GP$，$\\triangle GHP$ 為直角三角形：<br>$HP = \\sqrt{GH^2 + GP^2} = \\sqrt{20^2 + 99^2} = 101$<br>$\\triangle GHP$ 的周界 $= GH + GP + HP = 20 + 99 + 101 = 220$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q13",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Mensuration"],
        difficulty: 4,
        content: `(3分)<br>13. 現有兩實心金屬球體。較小的球體的表面面積與較大的球體的表面面積之比為4:9。<br>較大的球體的半徑為9cm。<br>把該兩球體熔化,並重鑄成兩實心直立圓錐體。將該兩圓錐體記為A及B。<br>已知 4 的高及底半徑分別為10cm及6cm。某學生得知B的底半徑<br>為12cm。該學生宣稱與B相似。該宣稱是否正確?試解釋你的答案。<br>(4分)<br>(a) 以表較小的球體的體積。<br>(b)`,
        hint: `(a) 長度比等於面積比的平方根，體積比等於長度比的立方。先求半徑再算體積。<br>(b) 圓錐體 B 的體積 = 兩球體總體積 - 圓錐體 A 的體積。檢查 $\\dfrac{V_B}{V_A} = \\left(\\dfrac{r_B}{r_A}\\right)^3$ 是否成立。`,
        solution: `<span class=\"q-label\">(a)</span> 相似比（半徑比）$= \\sqrt{\\dfrac{4}{9}} = \\dfrac{2}{3}$。<br>較小球體的半徑 $= 9 \\times \\dfrac{2}{3} = 6\\text{ cm}$。<br>較小球體的體積 $= \\dfrac{4}{3}\\pi (6)^3 = 288\\pi\\text{ cm}^3$。<br><br><span class=\"q-label\">(b)</span> 較大球體的體積 $= \\dfrac{4}{3}\\pi (9)^3 = 388\\pi\\text{ cm}^3$。兩球體總體積 $= 288\\pi + 388\\pi = 676\\pi\\text{ cm}^3$。<br>圓錐體 $A$ 的體積 $= \\dfrac{1}{3}\\pi (6)^2(10) = 120\\pi\\text{ cm}^3$。<br>圓錐體 $B$ 的體積 $= 676\\pi - 120\\pi = 1140\\pi\\text{ cm}^3$。<br>若 $A$ 與 $B$ 相似，體積比應為 $\\left(\\dfrac{r_B}{r_A}\\right)^3 = \\left(\\dfrac{12}{6}\right)^3 = 8$。<br>而實際體積比 $\\dfrac{1140\\pi}{120\\pi} = 9.5 \\neq 8$。<br>因此，圓錐體 $A$ 與圓錐體 $B$ 並不相似，該宣稱不正確。`
    },
{
        id: "2022-DSE-MATH-CP1-Q14",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Polynomials"],
        difficulty: 3,
        content: `設 $p(x)=2x^{3}+ax^{2}+bx-20$，其中 $a$ 及 $b$ 均為常數。當 $p(x)$ 除以 $x^2-2x+3$ 時，餘式為 $x+13$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $a$ 及 $b$。</div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">$x-5$ 是否 $p(x)$ 的因式？試解釋你的答案。</div></div><div class="q-line"><span class="q-label">(c)</span><div class="q-text-content">某人宣稱方程 $p(x)=0$ 有兩個無理根。你是否同意？試解釋你的答案。<span class="marks">(8分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 利用多項式長除法將 $p(x)$ 除以 $x^2-2x+3$，並將最後得到的餘式與 $x+13$ 的對應項係數進行比較，建立聯立方程求解 $a$ 與 $b$。<br>(b) 將 (a) 的答案代入 $p(x)$，計算 $p(5)$ 的值。若 $p(5)=0$，則 $x-5$ 是因式；否則不是。<br>(c) 利用因式定理將 $p(x)$ 寫成 $(x-5)(2x^2+mx+n)$ 的形式，再利用判別式 $\\Delta$ 及求根公式檢查剩餘二次方程的根是否為無理數。`,
        solution: `(a) 利用長除法，將 $2x^3+ax^2+bx-20$ 除以 $x^2-2x+3$：<br>商式為 $2x + (a+4)$<br>餘式為 $[b - 6 + 2(a+4)]x - 20 - 3(a+4) = (2a + b + 2)x - (3a + 32)$<br>已知餘式為 $x + 13$，比較係數得：<br>$\\begin{cases} 2a + b + 2 = 1 \\Rightarrow 2a + b = -1 \\\\ -(3a + 32) = 13 \\Rightarrow 3a = -45 \\Rightarrow a = -15 \\end{cases}$<br>將 $a = -15$ 代入第一個方程： $2(-15) + b = -1 \\Rightarrow b = 29$<br>所以 $a = -15$ 且 $b = 29$。<br><br>(b) 由 (a) 可得 $p(x) = 2x^3 - 15x^2 + 29x - 20$<br>計算 $p(5) = 2(5)^3 - 15(5)^2 + 29(5) - 20 = 250 - 375 + 145 - 20 = 0$<br>根據因式定理， $x-5$ 是 $p(x)$ 的因式。<br><br>(c) 因為 $x-5$ 為因式，利用長除法可將 $p(x)$ 因式分解為：<br>$p(x) = (x-5)(2x^2 - 5x + 4)$<br>令 $p(x) = 0$，則 $x = 5$（有理根）或 $2x^2 - 5x + 4 = 0$<br>對於二次方程 $2x^2 - 5x + 4 = 0$，其判別式為：<br>$\\Delta = (-5)^2 - 4(2)(4) = 25 - 32 = -7 < 0$<br>因為 $\\Delta < 0$，該方程沒有實根，更遑論無理根。<br>因此方程 $p(x)=0$ 只有一個實根（即有理根 5），並沒有兩個無理根，故不同意該宣稱。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q15",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Data Handling"],
        topic: ["Probability"],
        difficulty: 3,
        content: `某班有 10 名男生及 12 名女生。若從該班中隨機選出 4 名學生組成一個委員會，<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求該委員會有 2 名男生及 2 名女生的概率；</div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">求該委員會男生人數與女生人數不同的概率。<span class="marks">(4分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `全班總人數為 22 人，選出 4 人的總選法為 $C_{4}^{22}$。<br>(a) 從 10 名男生中選 2 人且從 12 名女生中選 2 人，方法數為 $C_{2}^{10} \\times C_{2}^{12}$。<br>(b) 男生與女生人數不同的餘事件為「男生與女生人數相同」（即各有 2 人），可直接利用 $1 - \\text{(a)的概率}$ 計算。`,
        solution: `(a) 隨機選出 4 名學生的總可能方法數 $= C_{4}^{22} = 7315$<br>有 2 名男生及 2 名女生的方法數 $= C_{2}^{10} \\times C_{2}^{12} = 45 \\times 66 = 2970$<br>所求的概率 $= \\dfrac{2970}{7315} = \\dfrac{54}{133}$。<br><br>(b) 男生與女生人數不同，其餘事件即為男生與女生人數相同（即 2 男 2 女）。<br>所求的概率 $= 1 - \\dfrac{54}{133} = \\dfrac{79}{133}$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q16",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Quadratic Functions"],
        difficulty: 4,
        content: `設 $g(x)=3x^{2}+12kx+16k^{2}+8$，其中 $k$ 為一非零的實常數。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">利用配方法，以 $k$ 表 $y=g(x)$ 的圖像的頂點的坐標。</div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">在同一直角坐標系中，將 $y=g(x)$ 的圖像的頂點及 $y=2g(-x)$ 的圖像的頂點分別記為 $A$ 及 $B$。設 $M$ 為 $AB$ 上的一點使得 $\\triangle OBM$ 的面積為 $\\triangle OAM$ 的面積之三倍，其中 $O$ 為原點。以 $k$ 表 $M$ 的坐標。<span class="marks">(5分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 將 $g(x)$ 提取前兩項的係數 3，然後加上並減去一次項係數一半的平方進行配方。<br>(b) 先寫出 $2g(-x)$ 的表達式並求出其頂點 $B$ 的坐標（或利用函數變換性質： $x \\to -x$ 為關於 $y$ 軸對稱，前面乘以 2 為 $y$ 坐標變為 2 倍）。由於 $\\triangle OBM$ 與 $\\triangle OAM$ 同高，其面積比等於底邊長度之比 $BM : AM = 3 : 1$，即 $M$ 是線段 $AB$ 的內分點，利用分點公式求 $M$。`,
        solution: `(a) $g(x) = 3(x^2 + 4kx) + 16k^2 + 8$<br>$= 3(x^2 + 4kx + 4k^2 - 4k^2) + 16k^2 + 8$<br>$= 3(x + 2k)^2 - 12k^2 + 16k^2 + 8$<br>$= 3(x + 2k)^2 + 4k^2 + 8$<br>所以頂點 $A$ 的坐標為 $(-2k, 4k^2 + 8)$。<br><br>(b) 考慮函數 $y = 2g(-x) = 2[3(-x + 2k)^2 + 4k^2 + 8] = 6(-x + 2k)^2 + 8k^2 + 16 = 6(x - 2k)^2 + 8k^2 + 16$<br>頂點 $B$ 的坐標為 $(2k, 8k^2 + 16)$。<br>已知 $\\triangle OBM \\text{ 的面積} = 3 \\times \\triangle OAM \\text{ 的面積}$，且 $M$ 位於線段 $AB$ 上，<br>因為兩個三角形共享頂點 $O$，故底邊長之比為 $BM : AM = 3 : 1$，即 $AM : MB = 1 : 3$。<br>由內分點公式，點 $M$ 的坐標為：<br>$x_M = \\dfrac{3x_A + 1x_B}{1 + 3} = \\dfrac{3(-2k) + 1(2k)}{4} = \\dfrac{-4k}{4} = -k$<br>$y_M = \\dfrac{3y_A + 1y_B}{1 + 3} = \\dfrac{3(4k^2 + 8) + 1(8k^2 + 16)}{4} = \\dfrac{12k^2 + 24 + 8k^2 + 16}{4} = \\dfrac{20k^2 + 40}{4} = 5k^2 + 10$<br>故 $M$ 的坐標為 $(-k, 5k^2 + 10)$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q17",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Arithmetic Sequences"],
        difficulty: 4,
        content: `設 $c$ 為一實常數。方程 $x^2+cx-9=0$ 的根為 $\\alpha$ 及 $\\beta$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">以 $c$ 表 $\\alpha^2+\\beta^2$。</div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">某等差數列的第 1 項、第 2 項及第 3 項分別為 $c^2$、 $\\alpha^2+\\beta^2$ 及 $85$。求 $n$ 的最小值使得該數列的首 $n$ 項之和大於 $2\\times 10^7$。<span class="marks">(7分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 由根與係數的關係可知 $\\alpha+\\beta = -c$ 且 $\\alpha\\beta = -9$。利用恆等式 $\\alpha^2+\\beta^2 = (\\alpha+\\beta)^2 - 2\\alpha\\beta$ 進行代換。<br>(b) 根據等差數列性質，第 2 項減第 1 項等於第 3 項減第 2 項，以此建立方程求出 $c^2$，進而求出首項 $a$ 和公差 $d$。最後列出首 $n$ 項和 $S_n > 2 \\times 10^7$ 的二次不等式求解 $n$。`,
        solution: `(a) 根據一元二次方程的根與係數關係（韋達定理）：<br>$\\alpha + \\beta = -c$<br>$\\alpha\\beta = -9$<br>因此， $\\alpha^2 + \\beta^2 = (\\alpha + \\beta)^2 - 2\\alpha\\beta = (-c)^2 - 2(-9) = c^2 + 18$。<br><br>(b) 已知等差數列的前三項為 $c^2$、 $c^2 + 18$、 $85$。<br>根據等差數列的性質（公差相等）：<br>$(c^2 + 18) - c^2 = 85 - (c^2 + 18)$<br>$18 = 67 - c^2 \\Rightarrow c^2 = 49$<br>因此，該數列的首項 $a = c^2 = 49$<br>第二項為 $49 + 18 = 67$，故公差 $d = 67 - 49 = 18$。<br>等差數列的首 $n$ 項之和 $S_n = \\dfrac{n}{2}[2a + (n-1)d] = \\dfrac{n}{2}[2(49) + (n-1)18] = \\dfrac{n}{2}[98 + 18n - 18] = \\dfrac{n}{2}[18n + 80] = 9n^2 + 40n$<br>根據題意，令 $S_n > 2 \\times 10^7$：<br>$9n^2 + 40n - 20000000 > 0$<br>解對應的二次方程 $9n^2 + 40n - 20000000 = 0$ 的正根：<br>$n = \\dfrac{-40 + \\sqrt{40^2 - 4(9)(-20000000)}}{2(9)} = \\dfrac{-40 + \\sqrt{1600 + 720000000}}{18} = \\dfrac{-40 + \\sqrt{720001600}}{18} \\approx \\dfrac{-40 + 26832.85}{18} \\approx 1488.49$<br>由於 $n$ 必須為正整數，當 $n \\ge 1489$ 時不等式成立。<br>所以 $n$ 的最小值為 1489。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q18",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Trigonometry"],
        difficulty: 5,
        content: `圖 2 中，把三角形紙卡 $PQR$ 懸掛使得 $PQ$ 位於水平地面上。已知 $PQ = 30\\text{ cm}$、 $PR=25\\text{ cm}$ 及 $\\angle QPR=95^\\circ$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求<div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">$QR$ 的長度，</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">$\\angle PQR$。</div></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">設 $M$ 為 $QR$ 的中點。某工匠得知 $PR$ 與水平地面間的交角為 $70^\\circ$。該工匠宣稱 $PM$ 與水平地面間的交角超過 $40^\\circ$。該宣稱是否正確？試解釋你的答案。<span class="marks">(7分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a)(i) 在 $\\triangle PQR$ 中已知兩邊及其夾角，直接利用餘弦定理求 $QR$。<br>(a)(ii) 利用正弦定理 $\\dfrac{\\sin\\angle PQR}{PR} = \\dfrac{\\sin\\angle QPR}{QR}$ 求解該角。<br>(b) 自 $R$ 作垂線 $RH$ 垂直於地面，則 $\\angle RPH = 70^{\\circ}$ 為 $PR$ 與地面的交角。利用直角 $\\triangle RPH$ 算出空間高度 $RH$。自 $M$ 作垂線 $MK \\perp \\text{地面}$，因為 $M$ 為 $QR$ 中點，由中點定理知 $MK = \\dfrac{1}{2}RH$。在 $\\triangle PQR$ 中利用餘弦定理求出中線 $PM$ 的長度，最後在直角 $\\triangle PKM$ 中求出 $\\sin\\angle MPK = \\dfrac{MK}{PM}$，算出交角並與 $40^{\\circ}$ 比較。`,
        solution: `(a)(i) 在 $\\triangle PQR$ 中，由餘弦定理：<br>$QR^2 = PQ^2 + PR^2 - 2(PQ)(PR)\\cos\\angle QPR$<br>$QR^2 = 30^2 + 25^2 - 2(30)(25)\\cos 95^{\\circ}$<br>$QR^2 = 900 + 625 - 1500(-0.087156) = 1525 + 130.734 = 1655.734$<br>$QR \\approx 40.691\\text{ cm}$（或 $40.7\\text{ cm}$）。<br><br>(a)(ii) 由正弦定理：<br>$\\dfrac{\\sin\\angle PQR}{PR} = \\dfrac{\\sin\\angle QPR}{QR}$<br>$\\dfrac{\\sin\\angle PQR}{25} = \\dfrac{\\sin 95^{\\circ}}{40.691} \\approx \\dfrac{0.99619}{40.691} \\approx 0.024482$<br>$\\sin\\angle PQR \\approx 25 \\times 0.024482 \\approx 0.61205$<br>$\\angle PQR \\approx 37.74^{\\circ}$（或 $37.7^{\\circ}$）。<br><br>(b) 設 $R$ 在水平地面上的投影點為 $H$，則 $RH \\perp \\text{地面}$。 $PR$ 與地面的交角為 $\\angle RPH = 70^{\\circ}$。<br>在直角 $\\triangle RPH$ 中， $RH = PR \\sin 70^{\\circ} = 25 \\sin 70^{\\circ} \\approx 23.4923\\text{ cm}$。<br>設 $M$ 在水平地面上的投影點為 $K$，則 $MK \\perp \\text{地面}$ 且 $MK // RH$。<br>因為 $M$ 是 $QR$ 的中點，根據三角形中點定理， $MK = \\dfrac{1}{2} RH \\approx \\dfrac{23.4923}{2} \\approx 11.7462\\text{ cm}$。<br>接著在 $\\triangle PQR$ 中求中線 $PM$ 的長度。利用餘弦定理於 $\\triangle PQM$ 中，其中 $QM = \\dfrac{1}{2} QR \\approx 20.3455\\text{ cm}$：<br>$PM^2 = PQ^2 + QM^2 - 2(PQ)(QM)\\cos\\angle PQR$<br>$PM^2 = 30^2 + (20.3455)^2 - 2(30)(20.3455)\\cos 37.738^{\\circ}$<br>$PM^2 = 900 + 413.94 - 1220.73(0.79084) = 1313.94 - 965.40 = 348.54$<br>$PM \\approx \\sqrt{348.54} \\approx 18.669\\text{ cm}$。<br>設 $PM$ 與水平地面間的交角為 $\\theta$，則在直角 $\\triangle PKM$ 中：<br>$\\sin\\theta = \\dfrac{MK}{PM} \\approx \\dfrac{11.7462}{18.669} \\approx 0.62918$<br>$\\theta = \\sin^{-1}(0.62918) \\approx 38.99^{\\circ}$。<br>因為 $38.99^{\\circ} \\le 40^{\\circ}$（沒有超過 $40^{\\circ}$），所以該工匠的宣稱不正確。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q19",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Equations of Circles"],
        difficulty: 5,
        content: `圓 $C$ 的圓心為點 $G(83, 112)$。得知點 $A(158, 12)$ 位於 $C$ 以外。 $AP$ 及 $AQ$ 分別為 $C$ 在點 $P$ 及點 $Q$ 的切線。已知 $C$ 通過點 $(23, 67)$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求通過 $A$ 及 $G$ 的直線的方程。</div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">求 $AG$ 與 $PQ$ 的交點的坐標。</div></div><div class="q-line"><span class="q-label">(c)</span><div class="q-text-content">求 $\\triangle APQ$ 的內切圓的方程。</div></div><div class="q-line"><span class="q-label">(d)</span><div class="q-text-content">某人宣稱 $\\triangle APQ$ 的內切圓的面積與外接圓的面積之比為 $1:4$。你是否同意？試解釋你的答案。<span class="marks">(12分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 已知兩點 $A(158, 12)$ 和 $G(83, 112)$，利用兩點式直接求出直線 $AG$ 的方程。<br>(b) 先利用圓心 $G$ 與圓上點 $(23, 67)$ 計算圓 $C$ 的半徑 $r$。依切線幾何性質， $AG \\perp PQ$，且交點 $K$ 滿足直角 $\\triangle APG$ 中的射影幾何關係 $GK \\cdot GA = r^2$。利用定比分點公式或向量求出 $K$ 點坐標。<br>(c) $\\triangle APQ$ 的內切圓圓心必位於對稱軸 $AG$ 上。利用切線長定理和角度關係，可發現切點 $K$ 實際上就是內切圓與 $PQ$ 的切點。利用幾何性質算得內切圓圓心 $I$ 坐標與半徑，寫出其圓方程。<br>(d) $\\triangle APQ$ 的外接圓即是以 $AG$ 為直徑的圓（因為 $\\angle APG = \\angle AQG = 90^{\\circ}$）。算出外接圓半徑 $R = \\dfrac{1}{2}AG$，並求出內切圓半徑 $r_in$ 與外接圓半徑 $R$ 的平方比，即可驗證面積比是否為 $1:4$。`,
        solution: `(a) 直線 $AG$ 通過 $A(158, 12)$ 及 $G(83, 112)$，其斜率為：<br>$m_{AG} = \\dfrac{112 - 12}{83 - 158} = \\dfrac{100}{-75} = -\\dfrac{4}{3}$<br>直線 $AG$ 的方程為：<br>$y - 12 = -\\dfrac{4}{3}(x - 158) \\Rightarrow 3y - 36 = -4x + 632 \\Rightarrow 4x + 3y - 668 = 0$。<br><br>(b) 圓 $C$ 的半徑平方 $r^2 = (83 - 23)^2 + (112 - 67)^2 = 60^2 + 45^2 = 3600 + 2025 = 5625$，故半徑 $r = 75$。<br>線段 $AG$ 的長度 $GA = \\sqrt{(158 - 83)^2 + (12 - 112)^2} = \\sqrt{75^2 + (-100)^2} = \\sqrt{5625 + 10000} = 125$。<br>設 $AG$ 與 $PQ$ 的交點為 $K$。由於 $AP$ 與 $AQ$ 為切線，根據對稱性， $AG \\perp PQ$。<br>在直角 $\\triangle APG$ 中， $PK \\perp AG$。由射影定理可知：<br>$GK \\cdot GA = r^2 \\Rightarrow GK \\times 125 = 5625 \\Rightarrow GK = 45$<br>因此， $KA = GA - GK = 125 - 45 = 80$。<br>這意味著點 $K$ 將線段 $GA$ 內分成 $GK : KA = 45 : 80 = 9 : 16$。<br>由分點公式求 $K$ 的坐標：<br>$x_K = \\dfrac{16x_G + 9x_A}{9 + 16} = \\dfrac{16(83) + 9(158)}{25} = \\dfrac{1328 + 1422}{25} = \\dfrac{2750}{25} = 110$<br>$y_K = \\dfrac{16y_G + 9y_A}{9 + 16} = \\dfrac{16(112) + 9(12)}{25} = \\dfrac{1792 + 108}{25} = \\dfrac{1900}{25} = 76$<br>所以交點 $K$ 的坐標為 $(110, 76)$。<br><br>(c) 設 $\\triangle APQ$ 的內切圓圓心為 $I$，半徑為 $R_{in}$。由於 $\\triangle APQ$ 關於直線 $AG$ 對稱，內切圓必與 $PQ$ 切於其中心點 $K(110, 76)$，且圓心 $I$ 位於直線 $AG$ 上。<br>在直角 $\\triangle APG$ 中， $AP = \\sqrt{GA^2 - r^2} = \\sqrt{125^2 - 75^2} = 100$。<br>且 $\\sin\\angle PAG = \\dfrac{r}{GA} = \\dfrac{75}{125} = \\dfrac{3}{5}$， $\\cos\\angle PAG = \\dfrac{4}{5}$。<br>因為 $AI$ 是 $\\angle PAQ$ 的角平分線，故 $\\angle IAK = \\angle PAG$。<br>在直角 $\\triangle AIK$ 中， $\\tan\\angle IAK = \\dfrac{\\sin\\angle PAG}{\\cos\\angle PAG} = \\dfrac{3}{4}$。<br>已知 $AK = 80$，所以內切圓半徑 $R_{in} = IK = AK \\cdot \\tan\\angle IAK = 80 \\times \\dfrac{3}{4} = 60$。<br>點 $I$ 位於線段 $KA$ 上，且 $KI = 60$， $IA = KA - KI = 80 - 60 = 20$。<br>因此 $KI : IA = 60 : 20 = 3 : 1$，即 $I$ 將線段 $KA$ 分成 $3:1$。<br>利用分點公式由 $K(110, 76)$ 和 $A(158, 12)$ 求 $I$：<br>$x_I = \\dfrac{1x_K + 3x_A}{1 + 3} = \\dfrac{110 + 3(158)}{4} = \\dfrac{110 + 474}{4} = 146$<br>$y_I = \\dfrac{1y_K + 3y_A}{1 + 3} = \\dfrac{76 + 3(12)}{4} = \\dfrac{76 + 36}{4} = 28$<br>所以內切圓方程為： $(x - 146)^2 + (y - 28)^2 = 60^2 \\Rightarrow (x - 146)^2 + (y - 28)^2 = 3600$。<br><br>(d) 因為 $\\angle APG = \\angle AQG = 90^{\\circ}$，根據圓周角逆定理， $\\triangle APQ$ 的外接圓即是以 $AG$ 為直徑的圓。<br>外接圓的半徑 $R_{out} = \\dfrac{1}{2} GA = \\dfrac{1}{2} (125) = 62.5$。<br>我們來計算內切圓面積與外接圓面積之比：<br>$\\dfrac{\\text{內切圓面積}}{\\text{外接圓面積}} = \\dfrac{\\pi R_{in}^2}{\\pi R_{out}^2} = \\left(\\dfrac{R_{in}}{R_{out}}\\right)^2 = \\left(\\dfrac{60}{62.5}\\right)^2 = \\left(\\dfrac{24}{25}\\right)^2 = \\dfrac{576}{625} \\neq \\dfrac{1}{4}$<br>因為面積比為 $576 : 625$ 而非 $1 : 4$，所以不同意該宣稱。`
    }
);
