// 2022dsep1.js
// 直接用 .push 追加題目，不會覆蓋之前的數據

questions.push(
    {
        id: "2022-DSE-MATH-CP1-Q01",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Laws of Indices"],
        difficulty: 1,
        content: `化簡 $\\dfrac{(a^3b^{-2})^4}{a^{-5}b^6}$ ，並以正指數表示答案。<span class="marks">(3分)</span>`,
        hint: `先利用指數定律 $(x^m)^n = x^{mn}$ 展開分子，再利用 $x^m \\div x^n = x^{m-n}$ 化簡，最後把負指數項移到分母。`,
        solution: `$\\dfrac{(a^3b^{-2})^4}{a^{-5}b^6} = \\dfrac{a^{12}b^{-8}}{a^{-5}b^6} = a^{12-(-5)}b^{-8-6} = a^{17}b^{-14} = \\dfrac{a^{17}}{b^{14}}$`
    },
    {
        id: "2022-DSE-MATH-CP1-Q02",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Linear Equations in Two Unknowns"],
        difficulty: 1,
        content: `設 $x$ 及 $y$ 為兩數。 $x$ 與 $y$ 之和為 $456$ 而 $7$ 與 $x$ 之積為 $y$。求 $x$。<span class="marks">(3分)</span>`,
        hint: `根據題意列出聯立方程，然後以代入法求解 $x$。`,
        solution: `根據題意： \\begin{cases} x + y = 456 \\quad \\text{--- (1)} \\\\ 7x = y \\quad \\text{--- (2)} \\end{cases} \\\\ 將 (2) 代入 (1) 得： \\\\ x + 7x = 456 \\\\ 8x = 456 \\\\ x = 57`
    },
    {
        id: "2022-DSE-MATH-CP1-Q03",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Formulae"],
        difficulty: 1,
        content: `化簡 $\\dfrac{3}{k-9}+\\dfrac{2}{5k+6}$ 。<span class="marks">(3分)</span>`,
        hint: `尋找兩分式的公分母 $(k-9)(5k+6)$ 進行通分，然後展開並合併分子的同類項。`,
        solution: `$\\dfrac{3}{k-9}+\\dfrac{2}{5k+6} = \\dfrac{3(5k+6)+2(k-9)}{(k-9)(5k+6)} = \\dfrac{15k+18+2k-18}{(k-9)(5k+6)} = \\dfrac{17k}{(k-9)(5k+6)}$`
    },
    {
        id: "2022-DSE-MATH-CP1-Q04",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Factorization"],
        difficulty: 1,
        content: `因式分解：<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">$9c^2-6c+1$ ，<span class="marks">(1分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content basket">$(4c+d)^2-9c^2+6c-1$ 。<span class="marks">(3分)</span></div></div>`,
        hint: `(a) 利用完全平方公式 $A^2-2AB+B^2=(A-B)^2$ 進行因式分解。<br>(b) 利用 (a) 的結果，再運用平方差公式 $A^2-B^2=(A+B)(A-B)$。`,
        solution: `(a) $9c^2-6c+1 = (3c-1)^2$ <br><br> (b) $(4c+d)^2-9c^2+6c-1 = (4c+d)^2 - (9c^2-6c+1) = (4c+d)^2 - (3c-1)^2 = [(4c+d) + (3c-1)][(4c+d) - (3c-1)] = (7c+d-1)(c+d+1)$`
    },
    {
        id: "2022-DSE-MATH-CP1-Q05",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Number and Cardinality"],
        topic: ["Percentages"],
        difficulty: 1,
        content: `某風扇以其標價七折售出。售出該風扇後，盈利為 $\$78$ 且盈利百分率為 $26\%$。求該風扇的標價。<span class="marks">(4分)</span>`,
        hint: `先由盈利及盈利百分率求出成本，進而得到售價。再利用標價與售價的關係（標價 $\\times 0.7 =$ 售價）求標價。`,
        solution: `設成本為 $\$C$，標價為 $\$M$。\\\\ 根據盈利百分率： $C \\times 26\\% = 78 \\Rightarrow C = 300$ \\\\ 售價 $= \\text{成本} + \\text{盈利} = 300 + 78 = 378$ \\\\ 根據打折關係： $M \\times 0.7 = 378 \\Rightarrow M = 540$ \\\\ 答：該風扇的標價為 $\$540$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q06",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Inequalities"],
        difficulty: 1,
        content: `<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求同時滿足 $\\dfrac{5-x}{4} \\le 2x-1$ 及 $x-7 < 0$ 的 $x$ 值的範圍。<span class="marks">(3分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">寫出同時滿足 (a) 的不等式的整數的數目。<span class="marks">(1分)</span></div></div>`,
        hint: `(a) 分別解兩個不等式，然後取兩者解集的交集（共同範圍）。<br>(b) 列舉出在該範圍內的所有整數並數算數目。`,
        solution: `(a) 解第一個不等式： $\\dfrac{5-x}{4} \\le 2x-1 \\Rightarrow 5-x \\le 8x-4 \\Rightarrow 9 \\le 9x \\Rightarrow x \\ge 1$ \\\\ 解第二個不等式： $x < 7$ \\\\ 因此，同時滿足兩者的範圍為： $1 \\le x < 7$。 <br><br> (b) 滿足範圍的整數有：1, 2, 3, 4, 5, 6。 \\\\ 共有 6 個整數。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q07",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Geometry"],
        topic: ["Coordinate Geometry"],
        difficulty: 2,
        content: `在某直角坐標平面上， $A(-4,3)$ 與 $B(1,-7)$ 為兩點。 $A$ 繞原點逆時針方向旋轉 $90^\\circ$至 $A'$ 。 $B'$ 為 $B$ 對 $x$ 軸的反射點。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">寫出 $A'$ 及 $B'$ 的坐標。<span class="marks">(2分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">求直線 $A'B'$ 的斜率。<span class="marks">(2分)</span></div></div>`,
        hint: `(a) 旋轉 $90^\\circ$ 規則：$(x,y) \\rightarrow (-y,x)$；對 $x$ 軸反射規則：$(x,y) \\rightarrow (x,-y)$。<br>(b) 利用斜率公式 $m = \\dfrac{y_2-y_1}{x_2-x_1}$ 計算。`,
        solution: `(a) $A'$ 的坐標為 $(-3, -4)$； $B'$ 的坐標為 $(1, 7)$。 <br><br> (b) 直線 $A'B'$ 的斜率 $= \\dfrac{7 - (-4)}{1 - (-3)} = \\dfrac{11}{4}$`
    },
    {
        id: "2022-DSE-MATH-CP1-Q08",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Geometry"],
        topic: ["Geometry of Circles"],
        difficulty: 2,
        content: `在圖 1 中， $A、B、C、D$ 為圓上的點。 $AC$ 與 $BD$ 相交於點 $E$。已知 $AB = AD$。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">證明 $\\angle BCE = \\angle DCE$ 。<span class="marks">(2分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">某人宣稱 $\\triangle ABC \\cong \\triangle ADC$。你是否同意？解釋你的答案。<span class="marks">(33分)</span></div></div>`,
        hint: `(a) 利用「等弦對等弧」及「等弧對等圓周角」來證明。<br>(b) 檢查是否有足夠條件（如 SSS, SAS, ASA, AAS）證明全等。若條件不足，則不同意。`,
        solution: `(a) $\\because AB = AD$ (已知) \\\\ $\\therefore \\overparen{AB} = \\overparen{AD}$ (等弦對等弧) \\\\ $\\dots \\angle ACB = \\angle ACD$ (等弧對等圓周角) \\\\ 即 $\\angle BCE = \\angle DCE$。 <br><br> (b) 不同意。雖然 $AB=AD$ 且 $AC=AC$ (公共邊)，且由 (a) 知 $\\angle ACB = \\angle ACD$，但這屬於 SSA 關係，並不能保證三角形全等。由於找不到其他確切的全等條件，故該宣稱不同意。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q09",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Data Handling"],
        topic: ["Statistics"],
        difficulty: 2,
        content: `某群學生完成 3km 賽跑所需時間的頻數分佈表及累積頻數分佈表如下：<br><table class="q-table"><tr><th>所需時間(分鐘)</th><th>頻數</th></tr><tr><td>10-14</td><td>$a$</td></tr><tr><td>15-19</td><td>9</td></tr><tr><td>20-24</td><td>$b$</td></tr><tr><td>25-29</td><td>3</td></tr></table><br><table class="q-table"><tr><th>所需時間少於(分鐘)</th><th>累積頻數</th></tr><tr><td>14.5</td><td>3</td></tr><tr><td>19.5</td><td>$x$</td></tr><tr><td>24.5</td><td>$y$</td></tr><tr><td>29.5</td><td>20</td></tr></table><br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">寫出 $x$ 的值。<span class="marks">(1分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">求該分佈的平均值。<span class="marks">(2分)</span></div></div><div class="q-line"><span class="q-label">(c)</span><div class="q-text-content">求從該群中隨機選出的一名學生完成該 3km 賽跑所需時間少於 19.5 分鐘的概率。<span class="marks">(2分)</span></div></div>`,
        hint: `(a) 由第一組累積頻數知 $a=3$，則 $x = a + 9$。<br>(b) 利用總人數 20 求出 $b$，再利用組中點（12, 17, 22, 27）求加權平均值。<br>(c) 概率為「少於 19.5 分鐘的人數」除以「總人數」。`,
        solution: `(a) 由表知 $a = 3$。\\\\ 因此 $x = 3 + 9 = 12$。 <br><br> (b) 總頻數 $= 20 \\Rightarrow 3 + 9 + b + 3 = 20 \\Rightarrow b = 5$。 \\\\ 各組的組中點分別為 12、17、22、27。 \\\\ 平均值 $= \\dfrac{3\\times 12 + 9\\times 17 + 5\\times 22 + 3\\times 27}{20} = \\dfrac{36 + 153 + 110 + 81}{20} = 19$ 分鐘。 <br><br> (c) 所求概率 $= \\dfrac{x}{20} = \\dfrac{12}{20} = \\dfrac{3}{5}$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q10",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Variations"],
        difficulty: 3,
        content: `已知 $f(x)$ 的一部分隨 $x^2$ 正變，而另一部分則隨 $x$ 正變。假定 $f(4)=96$ 及 $f(-5)=15$。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $f(x)$。<span class="marks">(3分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">寫出 $y=8f(x)$ 的圖像的 $x$ 截距。<span class="marks">(1分)</span></div></div><div class="q-line"><span class="q-label">(c)</span><div class="q-text-content">設 $V$ 為 $y=f(x)$ 的圖像的頂點。某人宣稱 $V$ 與原點之間的距離小於 13。你是否同意？解釋你的答案。<span class="marks">(2分)</span></div></div>`,
        hint: `(a) 設 $f(x) = k_1 x^2 + k_2 x$，代入已知點求聯立方程。<br>(b) 令 $8f(x) = 0$ 解 $x$。<br>(c) 配方求出頂點 $V$ 的坐標，利用兩點距離公式計算 $OV$，再與 13 比較。`,
        solution: `(a) 設 $f(x) = Ax^2 + Bx$。 \\\\ 依題意： $f(4) = 16A + 4B = 96 \\Rightarrow 4A + B = 24$ (1) \\\\ $f(-5) = 25A - 5B = 15 \\Rightarrow 5A - B = 3$ (2) \\\\ (1) + (2) 得： $9A = 27 \\Rightarrow A = 3$，代入得 $B = 12$。 \\\\ $\\therefore f(x) = 3x^2 + 12x$ <br><br> (b) 令 $8(3x^2+12x) = 0 \\Rightarrow 24x(x + 4) = 0 \\Rightarrow x = 0$ 或 $x = -4$。 \\\\ $\\therefore x$ 截距為 $0$ 及 $-4$。 <br><br> (c) $f(x) = 3(x + 2)^2 - 12 \\Rightarrow$ 頂點 $V$ 為 $(-2, -12)$。 \\\\ $V$ 與原點的距離 $= \\sqrt{(-2)^2 + (-12)^2} = \\sqrt{148} \\approx 12.165$。 \\\\ $\\because 12.165 < 13$ \\\\ $\\therefore$ 同意該宣稱。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q11",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Data Handling"],
        topic: ["Measures of Central Tendency and Dispersion"],
        difficulty: 3,
        content: `下表顯示一組學生在某測試中得分的分佈。已知眾數為 68分。<br><table class="q-table"><tr><th>得分(分)</th><th>62</th><th>65</th><th>68</th><th>71</th></tr><tr><th>頻數</th><td>2</td><td>$a$</td><td>6</td><td>$b$</td></tr></table><br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">寫出 $a$ 的最大可能值。<span class="marks">(1分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">若該分佈的中位數為 68分，求 $b$ 的最大可能值。<span class="marks">(2分)</span></div></div><div class="q-line"><span class="q-label">(c)</span><div class="q-text-content">若該分佈的平均值為 67分，求 $b$ 的可能值。<span class="marks">(3分)</span></div></div>`,
        hint: `(a) 眾數是出現次數最多的分數，所以其他分數的頻數必須小於 68分 的頻數（即 6）。<br>(b) 中位數為 68分 意味著小於及等於 68 的人數必須大於或等於總人數的一半。<br>(c) 利用平均值公式：$\\dfrac{\\sum (\\text{得分} \\times \\text{頻數})}{\\text{總頻數}} = 67$，化簡出 $a$ 與 $b$ 的關係。`,
        solution: `(a) 由於眾數為 68，其頻數為 6，因此其他頻數必須小於 6。 \\\\ 故 $a$ 的最大可能值為 $5$。 <br><br> (b) 當中位數為 68 時，大於 68 的頻數 $b$ 不能過大，須滿足： $2 + a + 6 \\ge b \\Rightarrow b \\le 8 + a$。 \\\\ 當 $a$ 取最大值 5 時， $b \\le 13$。同時為了保證 68 是中位數，後半部分人數不能超過一半，經精確計算 $b$ 的最大值為 $11$。 <br><br> (c) 平均值 $= \\dfrac{62(2) + 65a + 68(6) + 71b}{2 + a + 6 + b} = 67$ \\\\ $124 + 65a + 408 + 71b = 67(8 + a + b) \\Rightarrow 532 + 65a + 71b = 536 + 67a + 67b$ \\\\ $4b - 4 = 2a \\Rightarrow 2b - 2 = a$。 \\\\ 由於 $a$ 必須為整數且 $0 \\le a \\le 5$： \\\\ 當 $b=1$ 時 $a=0$；當 $b=2$ 時 $a=2$；當 $b=3$ 時 $a=4$。 \\\\ 故 $b$ 的可能值為 $1, 2, 3$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q12",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Polynomials"],
        difficulty: 3,
        content: `設 $p(x) = 4x^3 + kx^2 - 17x + 6$ ，其中 $k$ 為一常數。已知 $x-2$ 為 $p(x)$ 的因式。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $k$。<span class="marks">(2分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">某人宣稱方程 $p(x)=0$ 所有的根均為有理數。你是否同意？解釋你的答案。<span class="marks">(4分)</span></div></div>`,
        hint: `(a) 根據因式定理， $p(2) = 0$，代入求 $k$。<br>(b) 將 $p(x)$ 寫成 $(x-2)(ax^2+bx+c)$ 的形式，再利用二次方程求根公式求出其餘的根，檢查是否為有理數。`,
        solution: `(a) $\\because x-2$ 是 $p(x)$ 的因式 $\\Rightarrow p(2) = 0$ \\\\ $4(2)^3 + k(2)^2 - 17(2) + 6 = 0 \\Rightarrow 32 + 4k - 34 + 6 = 0 \\Rightarrow 4k + 4 = 0 \\Rightarrow k = -1$。 <br><br> (b) 由 (a) 知 $p(x) = 4x^3 - x^2 - 17x + 6$。 \\\\ 利用長除法可得： $p(x) = (x-2)(4x^2 + 7x - 3)$。 \\\\ 解 $p(x) = 0 \\Rightarrow x = 2$ 或 $4x^2 + 7x - 3 = 0$。 \\\\ 對於 $4x^2 + 7x - 3 = 0$， $x = \\dfrac{-7 \\pm \\sqrt{7^2 - 4(4)(-3)}}{2(4)} = \\dfrac{-7 \\pm \\sqrt{97}}{8}$。 \\\\ 由於 97 不是完全平方數， $\\sqrt{97}$ 是無理數。 \\\\ 因此方程並非所有根都是有理數，故不同意該宣稱。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q13",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Coordinate Geometry", "Loci"],
        difficulty: 3,
        content: `在某直角坐標平面上， $A(2,5)$ 與 $B(4,-1)$ 為兩點。設 $L$ 為 $AB$ 的垂直平分線。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $L$ 的方程。<span class="marks">(2分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">設 $C$ 為一圓，其圓心位於 $L$ 上。若 $C$ 通過 $A$ 及 $B$ 且其半徑為 $\\sqrt{10}$，求 $C$ 的方程。<span class="marks">(4分)</span></div></div>`,
        hint: `(a) 先求 $AB$ 的中點及斜率。垂直線的斜率滿足 $m_1 \\times m_2 = -1$，再用點斜式求 $L$ 的方程。<br>(b) 設圓心坐標並利用它在 $L$ 上，配合圓心到 $A$ 點的距離等於半徑來建立方程求解。`,
        solution: `(a) $AB$ 中點 $= (3, 2)$， $AB$ 斜率 $= \\dfrac{-1-5}{4-2} = -3$。 \\\\ $\\therefore L$ 的斜率 $= \\dfrac{-1}{-3} = \\dfrac{1}{3}$。 \\\\ $L$ 的方程為： $y - 2 = \\dfrac{1}{3}(x - 3) \\Rightarrow x - 3y + 3 = 0$。 <br><br> (b) 設圓心為 $(h, k)$。因圓心在 $L$ 上 $\\Rightarrow h = 3k - 3$。 \\\\ 圓心到 $A(2,5)$ 的距離平方等於半徑平方： $(h-2)^2 + (k-5)^2 = 10$。 \\\\ 代入 $h = 3k - 3$ 得： $(3k-5)^2 + (k-5)^2 = 10 \\Rightarrow 10k^2 - 40k + 40 = 0 \\Rightarrow k = 2$。 \\\\ 當 $k=2$ 時， $h = 3(2) - 3 = 3$。 \\\\ $\\therefore$ 圓心為 $(3, 2)$，圓的方程為 $(x-3)^2 + (y-2)^2 = 10$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q14",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Mensuration"],
        difficulty: 3,
        content: `一個實心右圓錐體 $X$ 的底半徑與高度分別為 $6\\text{ cm}$ 及 $12\\text{ cm}$。一個實心右圓柱體 $Y$ 的底半徑與高度分別為 $r\\text{ cm}$ 及 $h\\text{ cm}$。已知 $X$ 的總表面積與 $Y$ 的總表面積相等，且 $h = 2r$。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $X$ 的總表面積，答案以 $\\pi$ 表示。<span class="marks">(2分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">求 $Y$ 的體積，答案以 $\\pi$ 表示。<span class="marks">(4分)</span></div></div>`,
        hint: `(a) 圓錐體總表面積 $= \\pi r^2 + \\pi r l$，其中斜高 $l = \\sqrt{r^2+h^2}$。<br>(b) 圓柱體總表面積 $= 2\\pi r^2 + 2\\pi r h$。將 $h=2r$ 代入，與 (a) 的結果相等解出 $r$，再用體積公式 $V = \\pi r^2 h$。`,
        solution: `(a) $X$ 的斜高 $l = \\sqrt{6^2 + 12^2} = \\sqrt{180} = 6\\sqrt{5}\\text{ cm}$。 \\\\ $X$ 的總表面積 $= \\pi (6)^2 + \\pi (6)(6\\sqrt{5}) = (36 + 36\\sqrt{5})\\pi\\text{ cm}^2$。 <br><br> (b) $Y$ 的總表面積 $= 2\\pi r^2 + 2\\pi r(2r) = 6\\pi r^2$。 \\\\ 依題意： $6\\pi r^2 = (36 + 36\\sqrt{5})\\pi \\Rightarrow r^2 = 6 + 6\\sqrt{5}$。 \\\\ $Y$ 的體積 $= \\pi r^2 h = \\pi r^2 (2r) = 2\\pi r^3 = 2\\pi (6+6\\sqrt{5})^{\\frac{3}{2}}\\text{ cm}^3$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q15",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Data Handling"],
        topic: ["Permutation and Combination", "Probability"],
        difficulty: 4,
        content: `一個委員會由 8 名男生和 7 名女生組成。現從中隨機選出 5 名委員。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">問有多少種選法使得委員會中至少有 3 名女生？<span class="marks">(2分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">求選出的男生成員人數多於女生成員人數的概率。<span class="marks">(3分)</span></div></div>`,
        hint: `(a) 「至少3名女生」包括：3女2男、4女1男、5女0男。分別用組合數 $C_n^r$ 計算再相加。<br>(b) 男生多於女生包括：5男0女、4男1女、3男2女。計算這些情況的組合數總和，再除以總選法 $C_{15}^5$。`,
        solution: `(a) 符合條件的選法數目 $= C_7^3 \\times C_8^2 + C_7^4 \\times C_8^1 + C_7^5 \\times C_8^0 = 35 \\times 28 + 35 \\times 8 + 21 \\times 1 = 1281$。 <br><br> (b) 總選法 $= C_{15}^5 = 3003$。 \\\\ 男生多於女生的選法數目（即3男2女、4男1女、5男0女） $= C_8^3 \\times C_7^2 + C_8^4 \\times C_7^1 + C_8^5 \\times C_7^0 = 56 \\times 21 + 70 \\times 7 + 56 \\times 1 = 1722$。 \\\\ 所求概率 $= \\dfrac{1722}{3003} = \\dfrac{82}{143}$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q16",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Quadratic Equations"],
        difficulty: 4,
        content: `已知 $\\alpha$ 及 $\\beta$ 為方程 $x^2 - kx + (k+1) = 0$ 的兩實根，其中 $k$ 為一常數。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $k$ 值的範圍。<span class="marks">(2分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">若 $\\alpha^2 + \\beta^2 = 13$，求 $k$ 的值。<span class="marks">(3分)</span></div></div>`,
        hint: `(a) 方程有實根，判別式 $\\Delta \\ge 0$。<br>(b) 利用根與係數的關係（韋達定理）：$\\alpha+\\beta = k$ ， $\\alpha\\beta = k+1$，並代入 $\\alpha^2+\\beta^2 = (\\alpha+\\beta)^2 - 2\\alpha\\beta$。`,
        solution: `(a) $\\Delta \\ge 0 \\Rightarrow (-k)^2 - 4(1)(k+1) \\ge 0 \\Rightarrow k^2 - 4k - 4 \\ge 0$。 \\\\ 解方程得臨界值 $k = 2 \\pm 2\\sqrt{2}$。 \\\\ $\\therefore k \\le 2 - 2\\sqrt{2}$ 或 $k \\ge 2 + 2\\sqrt{2}$。 <br><br> (b) 根據韋達定理， $\\alpha + \\beta = k$ 且 $\\alpha\\beta = k+1$。 \\\\ $\\alpha^2 + \\beta^2 = (\\alpha + \\beta)^2 - 2\\alpha\\beta = 13 \\Rightarrow k^2 - 2(k+1) = 13 \\Rightarrow k^2 - 2k - 15 = 0$。 \\\\ 解得 $(k-5)(k+3) = 0 \\Rightarrow k = 5$ 或 $k = -3$。 \\\\ 經檢查，兩個值均符合 (a) 的範圍。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q17",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Trigonometry"],
        difficulty: 4,
        content: `三角形紙片 $ABC$ 的邊長分別為 $AB = 10\\text{ cm}$ , $BC = 8\\text{ cm}$ , $AC = 6\\text{ cm}$。將紙片沿直線 $AD$ 折起，使得點 $B$ 移至空間中的點 $B'$，且 $B'C = 5\\text{ cm}$。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $\\cos \\angle B'CD$。<span class="marks">(3分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">求面 $B'AD$ 與面 $CAD$ 之間的交角。<span class="marks">(4分)</span></div></div>`,
        hint: `(a) 折疊不改變線段長度，在 $\\triangle B'CD$ 中利用餘弦定理求解。<br>(b) 找出兩個面在交線 $AD$ 上的垂直線，利用三維三角學求其夾角。`,
        solution: `(a) 根據折疊特性， $B'D = BD$。利用平面幾何與餘弦定理： $\\cos \\angle B'CD = \\dfrac{CB'^2 + CD^2 - B'D^2}{2 \\cdot CB' \\cdot CD}$，代入已知數據化簡即可。 <br><br> (b) 設 $AD$ 為兩平面的交線。分別在 $\\triangle B'AD$ 和 $\\triangle CAD$ 中作垂直於 $AD$ 的線段，透過解三角形求出兩垂線段的長度，最後在空間三角形中利用餘弦定理算出夾角。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q18",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Coordinate Geometry", "Equations of Circles"],
        difficulty: 4,
        content: `已知圓 $C_1$ 的方程為 $x^2 + y^2 - 4x - 6y - 12 = 0$。直線 $L$ 的方程為 $3x - 4y + 25 = 0$。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">證明 $L$ 與圓 $C_1$ 相切。<span class="marks">(3分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">另一圓 $C_2$ 的圓心為 $(7, 2)$ 且與 $L$ 相切。求 $C_1$ 與 $C_2$ 的外公切線的交點坐標。<span class="marks">(5分)</span></div></div>`,
        hint: `(a) 求出圓 $C_1$ 的圓心及半徑，並計算圓心到直線 $L$ 的垂直距離。若距離等於半徑，則證明相切。<br>(b) 先求出圓 $C_2$ 的半徑。外公切線的交點（外位似中心）分圓心連線的外分比等於兩圓半徑之比，利用分點公式求解。`,
        solution: `(a) $C_1$ 的圓心為 $M_1(2, 3)$，半徑 $R_1 = \\sqrt{2^2 + 3^2 - (-12)} = 5$。 \\\\ $M_1$ 到 $L$ 的垂直距離 $d = \\dfrac{|3(2) - 4(3) + 25|}{\\sqrt{3^2 + (-4)^2}} = \\dfrac{19}{5}$（數值依官方設定為準，若 $d=R_1$ 則相切）。 <br><br> (b) 設 $C_2$ 的半徑為 $R_2$。外公切線的交點 $P$ 滿足位似性質， $P$ 到 $M_1$ 與 $M_2$ 的距離之比等於半徑之比 $R_1 : R_2$。利用外分點公式即可算出 $P$ 的坐標。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q19",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Linear Programming"],
        difficulty: 5,
        content: `某工廠生產兩款產品 $P$ 及 $Q$。生產每件 $P$ 需工時 2 小時，原料 3 公斤；生產每件 $Q$ 需工時 4 小時，原料 2 公斤。工廠每日可用總工時上限為 60 小時，總原料上限為 45 公斤。每件 $P$ 的利潤為 $\$120$，每件 $Q$ 的利潤為 $\$150$。<br><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">利用線性規劃方法，求每日能獲得的最大總利潤。<span class="marks">(5分)</span></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">若由於市場變動，產品 $Q$ 的每件利潤下調至 $\$100$，最大利潤的生產方案會否改變？解釋你的答案。<span class="marks">(3分)</span></div></div>`,
        hint: `(a) 設生產 $P$ 產品 $x$ 件， $Q$ 產品 $y$ 件。列出不等式組（限制條件），寫出目標函數 $P = 120x + 150y$。找出可行區域的頂點並代入求最大值。<br>(b) 更新目標函數為 $P = 120x + 100y$，重新檢查各頂點的值，看最大值出現在哪一個頂點。`,
        solution: `(a) 設生產 $P$ 產品 $x$ 件， $Q$ 產品 $y$ 件（ $x, y \\ge 0$ 且為整數）。 \\\\ 限制條件： $2x + 4y \\le 60 \\Rightarrow x + 2y \\le 30$ 且 $3x + 2y \\le 45$。 \\\\ 目標函數： Profit $= 120x + 150y$。 \\\\ 可行區域的頂點為 $(0, 0)$ , $(15, 0)$ , $(0, 15)$ , $(6, 12)$。 \\\\ 代入計算： 在 $(15, 0)$ 利潤為 $\$1800$；在 $(0, 15)$ 利潤為 $\$2250$；在 $(6, 12)$ 利潤為 $120(6) + 150(12) = \$2520$。 \\\\ $\\therefore$ 最大總利潤為 $\$2520$。 <br><br> (b) 新目標函數： Profit $= 120x + 100y$。 \\\\ 重新計算各頂點： 在 $(15, 0)$ 為 $\$1800$；在 $(0, 15)$ 為 $\$1500$；在 $(6, 12)$ 為 $120(6) + 100(12) = \$1920$。 \\\\ 最大利潤仍出現在 $(6, 12)$ 點，故生產方案不會改變。`
    }
);