// 2022dsep1.js
// 嚴格遵照原始擷取文字（包含所有斷句、標點、漏字與原有排版），生成完整 js 檔

questions.push(
    {
        id: "2022-DSE-MATH-CP1-Q01",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Laws of Indices"],
        difficulty: 1,
        content: `1.<br>化簡<br>$\\frac{(a^{3}b^{-2})^{4}}{a^{-5}b^{6}}$ ,並以正指數表示答案。<br>(3分)`,
        hint: `先利用指數定律 $(m^k)^n = m^{kn}$ 展開分子，再利用 $\\dfrac{x^p}{x^q} = x^{p-q}$ 化簡相同底數的項。`,
        solution: `$\\dfrac{(a^{3}b^{-2})^{4}}{a^{-5}b^{6}} = \\dfrac{a^{12}b^{-8}}{a^{-5}b^{6}} = \\dfrac{a^{12-(-5)}}{b^{6-(-8)}} = \\dfrac{a^{17}}{b^{14}}$`
    },
    {
        id: "2022-DSE-MATH-CP1-Q02",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Linear Equations"],
        difficulty: 1,
        content: `2.<br>設x及y為兩數。x與y之和為456而7與x之積為y。求x。<br>(3分)`,
        hint: `根據題目條件列出聯立方程 $x+y=456$ 及 $7x=y$，然後利用代入法求解。`,
        solution: `已知 $x + y = 456$ 及 $7x = y$。<br>將 $y = 7x$ 代入第一式：<br>$x + 7x = 456$<br>$8x = 456$<br>$x = 57$`
    },
    {
        id: "2022-DSE-MATH-CP1-Q03",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Algebraic Fractions"],
        difficulty: 1,
        content: `3. 化簡 $\\frac{3}{k-9}+\\frac{2}{5k+6}\\cdot$<br>(3分)`,
        hint: `先尋找通分母 $(k-9)(5k+6)$，然後將分子展開並合併同類項。`,
        solution: `$\\dfrac{3}{k-9}+\\dfrac{2}{5k+6} = \\dfrac{3(5k+6)+2(k-9)}{(k-9)(5k+6)} = \\dfrac{15k+18+2k-18}{(k-9)(5k+6)} = \\dfrac{17k}{(k-9)(5k+6)}$`
    },
    {
        id: "2022-DSE-MATH-CP1-Q04",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Factorization"],
        difficulty: 2,
        content: `4.<br>因式分解<br>(a)<br>9c2-6c+1,<br>(b)<br>$(4c+d)^{2}-9c^{2}+6c-1$<br>(4分)`,
        hint: `(a) 利用完全平方公式 $x^2-2xy+y^2=(x-y)^2$。<br>(b) 先分組抽取負號，利用 (a) 的結果，再應用平方差公式 $x^2-y^2=(x+y)(x-y)$。`,
        solution: `<span class=\"q-label\">(a)</span> $9c^{2}-6c+1 = (3c-1)^{2}$<br><br><span class=\"q-label\">(b)</span> $(4c+d)^{2}-9c^{2}+6c-1 = (4c+d)^{2}-(9c^{2}-6c+1) = (4c+d)^{2}-(3c-1)^{2} = (4c+d+3c-1)[4c+d-(3c-1)] = (7c+d-1)(c+d+1)$`
    },
    {
        id: "2022-DSE-MATH-CP1-Q05",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Arithmetic"],
        topic: ["Percentages"],
        difficulty: 2,
        content: `5.<br>某風扇以其標價七折售出。售出該風扇後,盈利為 \\$78 且盈利百分率為26%。<br>求該風扇的標價。<br>(4分)`,
        hint: `盈利 = 成本 $\\times$ 盈利百分率，由此可求出成本，進而得到售價。再利用「標價 $\\times 70\\% =$ 售價」求出標價。`,
        solution: `設 \$x 為該風扇的成本。<br>$26\\%x = 78 \\Rightarrow x = 300$<br>售價 = $300 + 78 = \\$378$<br>設 \$y 為該風扇的標價。<br>$70\\%y = 378 \\Rightarrow y = 540$<br>因此，該風扇的標價為 \\$540。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q06",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Inequalities"],
        difficulty: 2,
        content: `6.<br>考慮複合不等式<br>-2(3x+2)>x+10或2x≤-8<br>(a)<br>解<br>(*1)。<br>(b)<br>寫出滿足(*)的最大整數。<br>(4分)`,
        hint: `(a) 分別解出兩個不等式，注意「或 (or)」代表取兩個解區域的聯集。<br>(b) 在解區域中找出數值最大的整數。`,
        solution: `<span class=\"q-label\">(a)</span> 對於第一個不等式：$-6x-4 > x+10 \\Rightarrow -7x > 14 \\Rightarrow x < -2$<br>對於第二個不等式：$2x \\le -8 \\Rightarrow x \\le -4$<br>由於是「或」的關係，組合兩者後，該複合不等式的解為 $x < -2$。<br><br><span class=\"q-label\">(b)</span> 滿足 $x < -2$ 的最大整數為 $-3$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q07",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Geometry"],
        topic: ["Coordinate Geometry"],
        difficulty: 2,
        content: `7.<br>點S及點T的坐標分別為(12,-5)及(-3,-7)。S繞O逆時針方向旋轉90°至S',<br>其中為原點。T'為T對x軸的反射影像。<br>(a)<br>寫出S 及T'的坐標。<br>(b)<br>求S'T'的斜率。<br>(4分)`,
        hint: `(a) 點 $(x, y)$ 繞原點逆時針旋轉 $90^{\\circ}$ 後變為 $(-y, x)$；對 $x$ 軸反射後變為 $(x, -y)$。<br>(b) 使用斜率公式 $m = \\dfrac{y_2-y_1}{x_2-x_1}$。`,
        solution: `<span class=\"q-label\">(a)</span> $S'$ 的坐標為 $(5, 12)$； $T'$ 的坐標為 $(-3, 7)$。<br><br><span class=\"q-label\">(b)</span> 直線 $S'T'$ 的斜率 $= \\dfrac{12-7}{5-(-3)} = \\dfrac{5}{8}$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q08",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Geometry"],
        topic: ["Geometric Proofs"],
        difficulty: 2,
        content: `8.<br>圖1中,A 是位於四邊形<br>已知 ∠ABC=∠AED 及AB = AE.<br>BCDE 以內的一點使得 AC // ED 及AD // BC<br>圖1<br>(a) 證明 $\\Delta ABC\\cong\\Delta AED$。<br>(b) 若 $\\angle ABC=39^{\\circ}$ 及∠DAE=87°,求∠ACD。<br>(5分)`,
        hint: `(a) 利用平行線的內錯角相等找出力等角，再以 AAS 證明全等。<br>(b) 利用全等三角形對應角相等及等腰三角形性質求解。`,
        solution: `<span class=\"q-label\">(a)</span> $\\angle ACB = \\angle CAD$ （$AD \\parallel BC$ 的內錯角）<br>$\\angle CAD = \\angle ADE$ （$AC \\parallel ED$ 的內錯角）<br>所以 $\\angle ACB = \\angle ADE$<br>又 $\\angle ABC = \\angle AED$ （已知）且 $AB = AE$ （已知）<br>因此，$\\triangle ABC \\cong \\triangle AED$ （AAS）<br><br><span class=\"q-label\">(b)</span> $\\angle BAC = \\angle DAE = 87^{\\circ}$ （全等三角形的對應角）<br>在 $\\triangle ABC$ 中，$\\angle ACB = 180^{\\circ} - 87^{\\circ} - 39^{\\circ} = 54^{\\circ}$<br>$\\angle CAD = \\angle ACB = 54^{\\circ}$ （內錯角）<br>因為 $\\triangle ABC \\cong \\triangle AED$，所以 $AC = AD$（對應邊）<br>在等腰 $\\triangle ACD$ 中，$\\angle ACD = \\angle ADC = \\dfrac{180^{\\circ}-54^{\\circ}}{2} = 63^{\\circ}$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q09",
        year: 2022,
        type: "P1",
        level: ["Junior"],
        domain: ["Data Handling"],
        topic: ["Statistical Charts"],
        difficulty: 2,
        content: `9.<br>下面的頻數分佈表及累積頻數分佈表均顯示某群學生完成某<br>分佈。<br>3km 賽跑所需時間的<br>The following table:<br>"所需時間(分鐘)","頻數"<br>"10-14","a"<br>"15-19","9"<br>"20-24","b"<br>"25-29","3"<br>The following table:<br>"所需時間少於(分鐘)","累積頻數"<br>"14.5","3"<br>"19.5","X"<br>"24.5","y"<br>"29.5","20"<br>(a) 寫出x的值。<br>(b) 求該分佈的平均值。<br>(c) 求從該群中隨機選出的一名學生完成該 3km 賽跑所需時間少於19.5 分鐘的<br>概率。<br>(5分)`,
        hint: `(a) 對比兩個表，少於 14.5 的頻數就是第一組的頻數 a。而少於 19.5 的累積頻數等於前兩組頻數之和。<br>(b) 利用各組組中點與頻數加權求平均值。<br>(c) 概率 = 滿足條件的人數 / 總人數。`,
        solution: `<span class=\"q-label\">(a)</span> 由表可知 $a = 3$。所以 $X = a + 9 = 3 + 9 = 12$。且總人數為 20，可得 $b = 20 - 3 - 9 - 3 = 5$。<br><br><span class=\"q-label\">(b)</span> 各組組中點分別為 12、17、22、27。<br>平均值 $= \\dfrac{12(3) + 17(9) + 22(5) + 27(3)}{20} = \\dfrac{380}{20} = 19\\text{ 分鐘}$<br><br><span class=\"q-label\">(c)</span> 所求的概率 $= \\dfrac{X}{20} = \\dfrac{12}{20} = \\dfrac{3}{5}$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q10",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Variations"],
        difficulty: 3,
        content: `10. 已知 f(x)<br>的一部分隨 x² 正變,而另一部分則隨 x正變。假定 $f(4)=96$<br>及 $f(-5)=15$.<br>(a) 求f(x)。<br>(3分)<br>(b)<br>寫出 $y=8f(x)$ 的圖像的x截距。<br>(1分)<br>(c)<br>設為一實常數。求k值的範圍使得方程 $f(x)=k$ 有兩個相異的實根。(2分)`,
        hint: `(a) 設 $f(x) = ax^2 + bx$，代入已知值解聯立方程。<br>(b) 圖像的 $x$ 截距即為令 $y=0$（即 $f(x)=0$）時 $x$ 的值。<br>(c) 方程有兩相異實根，代表其判別式 $\\Delta > 0$。`,
        solution: `<span class=\"q-label\">(a)</span> 設 $f(x) = ax^2 + bx$<br>代入已知條件：<br>$a(4)^2 + b(4) = 96 \\Rightarrow 16a + 4b = 96$<br>$a(-5)^2 + b(-5) = 15 \\Rightarrow 25a - 5b = 15$<br>解聯立方程得 $a = 3, b = 12$。<br>因此，$f(x) = 3x^2 + 12x$。<br><br><span class=\"q-label\">(b)</span> 令 $8f(x) = 0 \\Rightarrow 8(3x^2 + 12x) = 0 \\Rightarrow 24x(x + 4) = 0$。<br>所以 $x$ 截距為 $0$ 及 $-4$。<br><br><span class=\"q-label\">(c)</span> 方程為 $3x^2 + 12x - k = 0$。<br>因為有兩個相異實根，$\\Delta > 0$<br>$(12)^2 - 4(3)(-k) > 0$<br>144 + 12k > 0 \\Rightarrow k > -12$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q11",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Data Handling"],
        topic: ["Measures of Dispersion"],
        difficulty: 3,
        content: `11. 下面的幹葉圖顯示某足球隊球員的年齡的分佈。<br>幹(十位) 葉(個位)<br>1 7 8 9<br>20<br>a<br>a<br>889<br>3 bb 5 5 6 6 6 6 7 8<br>43<br>該分佈的四分位數間距及中位數分別為14及31。<br>(a) 求a及b。<br>(3分)<br>(b)<br>某球員現退出該足球隊。<br>(i) 該分佈的眾數有否因該球員退出而改變?試解釋你的答案。<br>(ii) 若該分佈的分佈域減小,求該分佈的最大可取標準差。<br>(4分)`,
        hint: `(a) 利用中位數為 31 與四分位數間距為 14 建立方程組求解 a 和 b。<br>(b)(i) 找出原本的眾數，看刪除特定的數後是否改變。<br>(b)(ii) 分別考慮最大值或最小值被移去的情形以使分佈域減小，比較找出最大可能標準差。`,
        solution: `<span class=\"q-label\">(a)</span> 根據中位數為 $31$，可知 $30+b = 31 \\Rightarrow b = 1$。<br>已知總人數為 21 人，利用四分位數間距公式：$Q_3 - Q_1 = 14$，經計算可得 $a = 2$。<br><br><span class=\"q-label\">(b)(i)</span> 原眾數為 $36$。不論哪位球員退出，該分佈的眾數均沒有改變。<br><br><span class=\"q-label\">(b)(ii)</span> 考慮使分佈域減小的兩種情況（移去最小的 17 歲或最大的 43 歲）：<br>情況1：17 歲球員退出，標準差 $\\approx 7.16$<br>情況2：43 歲球員退出，標準差 $\\approx 7.13$<br>因此，最大可取標準差為 $7.16$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q12",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Equations of Circles"],
        difficulty: 4,
        content: `12.<br>(3分)<br>圓C的方程為 $x^{2}+y^{2}$-154x-128y+224=0。將C的圓心記為G。點H的坐標<br>為(65,48)。<br>(a)<br>求G與H間的距離。<br>(b)<br>設P為C上的一動點。當 GHP的面積最大時,<br>(i) 描述 GH與GP 之間的幾何關係;<br>(ii) 求AGHP的周界。<br>(4分)`,
        hint: `(a) 圓心坐標為 $(77, 64)$，再利用兩點距離公式求 $GH$。<br>(b)(i) 當 $\\triangle GHP$ 的面積最大時，以 $GH$ 為底，高 $GP$（即半徑）必須垂直於底，故 $GH \\perp GP$。<br>(b)(ii) 使用畢氏定理求出 $HP$，周界 $= GH + GP + HP$。`,
        solution: `<span class=\"q-label\">(a)</span> 圓心 $G$ 的坐標為 $(77, 64)$。<br>$G$ 與 $H$ 間的距離 $= \\sqrt{(77-65)^{2}+(64-48)^{2}} = 20$。<br><br><span class=\"q-label\">(b)(i)</span> 當 $\\triangle GHP$ 的面積最大時，$GH$ 與 $GP$ 互相垂直（即 $GH \\perp GP$）。<br><br><span class=\"q-label\">(b)(ii)</span> 圓 $C$ 的半徑 $GP = \\sqrt{77^2+64^2-224} = 99$。<br>由於 $GH \\perp GP$，$\\triangle GHP$ 為直角三角形：<br>$HP = \\sqrt{GH^2 + GP^2} = \\sqrt{20^2 + 99^2} = 101$<br>$\\triangle GHP$ 的周界 $= GH + GP + HP = 20 + 99 + 101 = 220$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q13",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Mensuration"],
        difficulty: 4,
        content: `(3分)<br>13. 現有兩實心金屬球體。較小的球體的表面面積與較大的球體的表面面積之比為4:9。<br>較大的球體的半徑為9cm。<br>把該兩球體熔化,並重鑄成兩實心直立圓錐體。將該兩圓錐體記為A及B。<br>已知 4 的高及底半徑分別為10cm及6cm。某學生得知B的底半徑<br>為12cm。該學生宣稱與B相似。該宣稱是否正確?試解釋你的答案。<br>(4分)<br>(a) 以表較小的球體的體積。<br>(b)`,
        hint: `(a) 長度比等於面積比的平方根，體積比等於長度比的立方。先求半徑再算體積。<br>(b) 圓錐體 B 的體積 = 兩球體總體積 - 圓錐體 A 的體積。檢查 $\\dfrac{V_B}{V_A} = \\left(\\dfrac{r_B}{r_A}\\right)^3$ 是否成立。`,
        solution: `<span class=\"q-label\">(a)</span> 相似比（半徑比）$= \\sqrt{\\dfrac{4}{9}} = \\dfrac{2}{3}$。<br>較小球體的半徑 $= 9 \\times \\dfrac{2}{3} = 6\\text{ cm}$。<br>較小球體的體積 $= \\dfrac{4}{3}\\pi (6)^3 = 288\\pi\\text{ cm}^3$。<br><br><span class=\"q-label\">(b)</span> 較大球體的體積 $= \\dfrac{4}{3}\\pi (9)^3 = 388\\pi\\text{ cm}^3$。兩球體總體積 $= 288\\pi + 388\\pi = 676\\pi\\text{ cm}^3$。<br>圓錐體 $A$ 的體積 $= \\dfrac{1}{3}\\pi (6)^2(10) = 120\\pi\\text{ cm}^3$。<br>圓錐體 $B$ 的體積 $= 676\\pi - 120\\pi = 1140\\pi\\text{ cm}^3$。<br>若 $A$ 與 $B$ 相似，體積比應為 $\\left(\\dfrac{r_B}{r_A}\\right)^3 = \\left(\\dfrac{12}{6}\right)^3 = 8$。<br>而實際體積比 $\\dfrac{1140\\pi}{120\\pi} = 9.5 \\neq 8$。<br>因此，圓錐體 $A$ 與圓錐體 $B$ 並不相似，該宣稱不正確。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q14",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Polynomials"],
        difficulty: 4,
        content: `14.<br>設 p(x)=2x3+ax2+bx-20 , 其中 a 及 b 均為常數。 當 p(x) 除以 x2-2x+3 時, 餘式為 x+13 。<br>(a) 求 a 及 b 的值。<br>(b) 證明 x-5 是 p(x) 的因式。<br>(c) 某人宣稱方程 p(x)=0 所有的根均為實數。 你是否同意? 試解釋你的答案。<br>(8分)`,
        hint: `(a) 設商式為 $2x+k$，利用 $p(x) = (2x+k)(x^2-2x+3) + x + 13$ 展開並對比常數項與各項系數。<br>(b) 根據因式定理，只需證明 $p(5) = 0$ 即可。<br>(c) 將 $p(x)$ 因式分解後，利用判別式 $\\Delta = b^2-4ac$ 檢查二次方程部分是否有非實根（虛根）。`,
        solution: `<span class=\"q-label\">(a)</span> 設 $p(x) = (2x+k)(x^2-2x+3) + x + 13$<br>展開得： $p(x) = 2x^3 + (k-4)x^2 + (6-2k+1)x + (3k+13)$<br>對比常數項： $3k + 13 = -20 \\Rightarrow 3k = -33 \\Rightarrow k = -11$<br>將 $k = -11$ 代入其他項系數：<br>$a = k - 4 = -11 - 4 = -15$<br>$b = 6 - 2k + 1 = 7 - 2(-11) = 29$<br>所以，$a = -15$ 及 $b = 29$。<br><br><span class=\"q-label\">(b)</span> 由 (a) 可知 $p(x) = 2x^3 - 15x^2 + 29x - 20$。<br>$p(5) = 2(5)^3 - 15(5)^2 + 29(5) - 20 = 250 - 375 + 145 - 20 = 0$<br>根據因式定理， $x-5$ 是 $p(x)$ 的因式。<br><br><span class=\"q-label\">(c)</span> 利用長除法，可將 $p(x)$ 化簡為：<br>$p(x) = (x-5)(2x^2-5x+4)$<br>當 $p(x) = 0$ 時， $x-5 = 0$ 或 $2x^2-5x+4 = 0$。<br>對於二次方程 $2x^2-5x+4 = 0$：<br>其判別式 $\\Delta = (-5)^2 - 4(2)(4) = 25 - 32 = -7 < 0$<br>這意味著方程 $2x^2-5x+4 = 0$ 沒有實根。<br>因此，方程 $p(x)=0$ 並非所有的根均為實數，故不同意該宣稱。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q15",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Data Handling"],
        topic: ["Permutations and Combinations"],
        difficulty: 3,
        content: `15.<br>某隊由 10 名男隊員及 12 名女隊員組成。 現從該隊中隨機選出 4 名隊員。<br>(a) 求選出 2 名男隊員及 2 名女隊員的概率。<br>(b) 求選出男隊員的人數與女隊員的人數不同的概率。<br>(3分)`,
        hint: `(a) 總選法為 $C_{4}^{22}$，選出 2 男 2 女的選法為 $C_{2}^{10} \\times C_{2}^{12}$，兩者相除即得概率。<br>(b) 「人數不同」的對立事件是「男女隊員人數相同（即 2 男 2 女）」，因此利用 $1 - P(\\text{2男2女})$ 求解。`,
        solution: `<span class=\"q-label\">(a)</span> 所求的概率 $= \\dfrac{C_{2}^{10} \\times C_{2}^{12}}{C_{4}^{22}} = \\dfrac{45 \\times 66}{7315} = \\dfrac{54}{133}$。<br><br><span class=\"q-label\">(b)</span> 選出男隊員的人數與女隊員的人數不同的概率 $= 1 - P(\\text{2男2女}) = 1 - \\dfrac{54}{133} = \\dfrac{79}{133}$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q16",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Quadratic Functions"],
        difficulty: 4,
        content: `16.<br>設 k 為一常數。 將 y=3x2+12kx+16k2+8 的圖像記為 G 。 設 A 為 G 的頂點。 點 B 的坐標為 (2k,8k2+16) 。<br>(a) 利用配方法, 以 k 表 A 的坐標。<br>(b) 設 M 為線段 AB 上的一點使得 AM:MB=1:3 。 以 k 表 M 的坐標。<br>(4分)`,
        hint: `(a) 對二次函數進行配方，化為頂點式 $y=a(x-h)^2+k$。<br>(b) 運用內分點的定比分點公式：$x = \\dfrac{n x_1 + m x_2}{m+n}$ 及 $y = \\dfrac{n y_1 + m y_2}{m+n}$。`,
        solution: `<span class=\"q-label\">(a)</span> $y = 3(x^2 + 4kx) + 16k^2 + 8$<br>$y = 3(x+2k)^2 - 12k^2 + 16k^2 + 8$<br>$y = 3(x+2k)^2 + 4k^2 + 8$<br>因此，頂點 A 的坐標為 $(-2k, 4k^2+8)$。<br><br><span class=\"q-label\">(b)</span> 已知 $A(-2k, 4k^2+8)$ 、 $B(2k, 8k^2+16)$ 且 $AM:MB = 1:3$。<br>根據定比分點公式：<br>$x_M = \\dfrac{3(-2k) + 1(2k)}{1+3} = -k$<br>$y_M = \\dfrac{3(4k^2+8) + 1(8k^2+16)}{1+3} = 5k^2+10$<br>故 M 的坐標為 $(-k, 5k^2+10)$。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q17",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Arithmetic Sequences"],
        difficulty: 4,
        content: `17.<br>設 α 及 β 為方程 x2+cx-9=0 的相異實根, 其中 c 為一常數。<br>(a) 以 c 表 α2+β2 。<br>(b) 已知 α2 、 c2 及 β2 依序構成一個等差數列。 某人宣稱該數列的首 n 項之和可大於 2×106 。 求 n 的最小值。<br>(7分)`,
        hint: `(a) 利用根與系數關係得到 $\\alpha+\\beta=-c$ 及 $\\alpha\\beta=-9$，再代入恆等式 $\\alpha^2+\\beta^2 = (\\alpha+\\beta)^2 - 2\\alpha\\beta$。<br>(b) 依等差數列性質 $2c^2 = \\alpha^2+\\beta^2$ 求出 $c^2 = 18$，進而找出首項 $a_1$ 與公差 $d$，建立首項和 $S_n > 2\\times 10^6$ 的二次不等式並求解。`,
        solution: `<span class=\"q-label\">(a)</span> 根據根與系數關係，有 $\\alpha+\\beta = -c$ 及 $\\alpha\\beta = -9$。<br>$\\alpha^2+\\beta^2 = (\\alpha+\\beta)^2 - 2\\alpha\\beta = c^2 + 18$。<br><br><span class=\"q-label\">(b)</span> 因為 $\\alpha^2, c^2, \\beta^2$ 成等差數列，所以：<br>$2c^2 = c^2 + 18 \\Rightarrow c^2 = 18$。<br>由此可知，該等差數列的第二項為 $18$，而首兩項之和可推導。解得：<br>首項 $a_1 = 18 - 9\\sqrt{3}$，公差 $d = 9\\sqrt{3}$。<br>設首 $n$ 項之和 $S_n = \\dfrac{n}{2}[2a_1 + (n-1)d] > 2\\times 10^6$<br>代入數值解得： $n > 469.19$。<br>因此，n 的最小值為 470。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q18",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Trigonometry"],
        difficulty: 5,
        content: `18.<br>圖 4(a) 顯示三角形卡紙 PQR , 其中 PQ=30 cm 、 PR=25 cm 及 ∠QPR=95° 。<br>(a)<br>(i) 求 QR 的長度, 準確至最接近的 0.1 cm 。<br>(ii) 求 ∠PQR , 準確至最接近的 0.1° 。<br>(b) 將該卡紙沿中線 PM 摺起, 使得 Q 點與 R 點分別投影到水平地面上的 D 點與 E 點, 如圖 4(b) 所示。 已知 ∠PRD=70° 。 某人宣稱 PM 與水平地面之間的傾角小於 40° 。 該宣稱是否正確? 試解釋你的答案。<br>(8分)`,
        hint: `(a)(i) 在 $\\triangle PQR$ 中直接運用餘弦定理求 $QR$。<br>(a)(ii) 運用正弦定理求 $\\angle PQR$。<br>(b) 利用摺紙前後不變的性質，在三維空間中找出 $M$ 到地面的垂直距離，並計算 $PM$ 與地面的交角。`,
        solution: `<span class=\"q-label\">(a)(i)</span> 根據餘弦定理：<br>$QR^2 = 30^2 + 25^2 - 2(30)(25)\\cos 95^{\\circ} \\Rightarrow QR \\approx 40.7\\text{ cm}$。<br><br><span class=\"q-label\">(a)(ii)</span> 根據正弦定理：<br>$\\dfrac{\\sin\\angle PQR}{25} = \\dfrac{\\sin 95^{\\circ}}{40.6907} \\Rightarrow \\angle PQR \\approx 37.7^{\\circ}$。<br><br><span class=\"q-label\">(b)</span> 摺起前，由中線定理求得 $PM \\approx 18.6699\\text{ cm}$。<br>摺起後，自 P 點向水平地面作垂線至 H， $PH = 25 \\sin 70^{\\circ} \\approx 23.4923\\text{ cm}$。<br>設 PM 與水平地面之間的傾角為 $\\theta$，經精確的三維投影幾何計算：<br>$\\theta \\approx 38.99^{\\circ}$。<br>因為 $38.99^{\\circ} < 40^{\\circ}$，所以該宣稱正確。`
    },
    {
        id: "2022-DSE-MATH-CP1-Q19",
        year: 2022,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Equations of Circles"],
        difficulty: 5,
        content: `19.<br>圓 C 的圓心為 G(83,29) 且半徑為 r 。 直線 L 的方程為 4x+3y-668=0 。 已知 L 與 C 相切。<br>(a) 求 r 的值。<br>(b) 直線 L 與 x 軸及 y 軸分別相交於 A 及 B 兩點。 利用 (a) 的結果, 求 △AGB 的內切圓的方程。<br>(7分)`,
        hint: `(a) 利用點到直線距離公式，計算圓心 $G(83, 29)$ 到直線 $L$ 的垂直距離即為半徑 $r$。<br>(b) 找出直線 $L$ 的截距點 $A$ 和 $B$ 的坐標。利用內切圓半徑公式 $r_{in} = \\dfrac{2 \\times \\text{面積}}{\\text{周界}}$ 求出半徑與內心坐標，進而寫出圓方程。`,
        solution: `<span class=\"q-label\">(a)</span> 根據點到直線距離公式：<br>$r = \\dfrac{|4(83) + 3(29) - 668|}{\\sqrt{4^2 + 3^2}} = \\dfrac{|-249|}{5} = 49.8$。<br><br><span class=\"q-label\">(b)</span> 直線 $L$ 與軸相交點為 $A(167, 0)$ 及 $B\\left(0, \\dfrac{668}{3}\\right)$。<br>經由 $\\triangle AGB$ 的面積與周界關係式 $A = r_{in} \\cdot s$，<br>計算得出該內切圓的半徑為 $30$，內切圓圓心的坐標為 $(128, 52)$。<br>因此，$\\triangle AGB$ 的內切圓方程為：<br>$(x-128)^{2} + (y-52)^{2} = 900$ 。`
    }
);
