// 2023dsep1.js
// 直接用 .push 追加題目，不會覆蓋之前的數據
questions.push(
    {
        id: "2023-DSE-MATH-CP1-Q01",
        year: 2023,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Formulae"],
        difficulty: 1,
        content: `令 $h$ 成為公式 $\\dfrac{5}{h+k}=\\dfrac{k}{h-3}$ 的主項。`,
        hint: `交叉相乘展開方程，將所有含有 $h$ 的項移到等號左邊，抽公因式後即可單獨導出 $h$。`,
        solution: `$5(h-3) = k(h+k) \\Rightarrow 5h - 15 = kh + k^2 \\Rightarrow 5h - kh = k^2 + 15 \\Rightarrow h(5-k) = k^2 + 15 \\Rightarrow h = \\dfrac{k^2+15}{5-k}$`
    },
    {
        id: "2023-DSE-MATH-CP1-Q02",
        year: 2023,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Laws of Indices"],
        difficulty: 1,
        content: `化簡 $\\dfrac{x^{-8}y}{(x^{7}y^{9})^{-6}}$ ，並以正指數表示答案。`,
        hint: `先處理分母的負整數冪次分配律，然後再根據底數相同相除時指數相減的法則進行化簡。`,
        solution: `原式 $= \\dfrac{x^{-8}y}{x^{-42}y^{-54}} = x^{-8-(-42)}y^{1-(-54)} = x^{34}y^{55}$`
    },
    {
        id: "2023-DSE-MATH-CP1-Q03",
        year: 2023,
        type: "P1",
        level: ["Junior"],
        domain: ["Number and Measures"],
        topic: ["Estimation and Error"],
        difficulty: 2,
        content: `若一包芝士的重量量得 $220\\text{g}$ 準確至最接近的 $10\\text{g}$，則稱它為普通裝。某人宣稱 $250$ 包普通裝芝士的總重量可量得 $53.6\\text{kg}$ 準確至最接近的 $0.1\\text{kg}$。該宣稱是否正確？試解釋你的答案。`,
        hint: `找出單包普通裝芝士的最大可取值上限，乘上 $250$ 包得到總重上限，再與宣稱重量的最上限作比較。`,
        solution: `單包普通裝最大可取重量 $< 225\\text{g}$。$250$ 包的總重量 $< 225 \\times 250 = 56250\\text{g} = 56.25\\text{kg}$。而宣稱的 $53.6\\text{kg}$ 範圍為 $53.55\\text{kg} \\le W < 53.65\\text{kg}$，兩者範圍有重疊，故宣稱有可能正確。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q04",
        year: 2023,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Linear Inequalities and Compound Inequalities"],
        difficulty: 2,
        content: `考慮複合不等式 $3x+2>\\dfrac{4x-5}{2}$ 及 $3x-2<7 \\quad (*)$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">解 $(*)$。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">有多少個負整數滿足 $(*)$？<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 分別解出兩個不等式並取交集（及 / and）；(b) 在解的範圍內數出負整數的數量。`,
        solution: `(a) 第一個：$6x+4 > 4x-5 \\Rightarrow 2x > -9 \\Rightarrow x > -4.5$。第二個：$3x < 9 \\Rightarrow x < 3$。共同範圍為 $-4.5 < x < 3$。<br>(b) 負整數有 $-4, -3, -2, -1$，共 $4$ 個。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q05",
        year: 2023,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Percentages"],
        difficulty: 2,
        content: `某百貨內有一隻公仔。該公仔的折實價為 $\\$576$，為其標價的八折。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求該公仔的標價。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">售出該公仔所獲取的利潤百分率為 $20\\%$。求該公仔的成本。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 標價 $\\times 0.8 = 576$；(b) 成本 $\\times (1 + 20\\%) = 576$。`,
        solution: `(a) 標價 $= 576 / 0.8 = \\$720$。<br>(b) 成本 $= 576 / 1.2 = \\$480$。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q06",
        year: 2023,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Rates, Ratios and Proportions"],
        difficulty: 2,
        content: `設 $a$、 $b$ 及 $c$ 為正整數使得 $a:b=6:7$ 及 $b:c=8:9$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $a:b:c$。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">已知 $a$、 $b$ 及 $c$ 的最小公倍數為 $1008$。求 $c$。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 利用通分母的方法將 $b$ 的比例項化為相同數值（7和8的最小公倍數是56）；(b) 設 $a=48k, b=56k, c=63k$，找出它們的最小公倍數代數式求 $k$。`,
        solution: `(a) $a:b = 48:56$, $b:c = 56:63 \\Rightarrow a:b:c = 48:56:63$。<br>(b) 設 $a=48k, b=56k, c=63k$。因 $48, 56, 63$ 的最小公倍數是 $1008$，故 $\\text{LCM}(a,b,c) = 1008k = 1008 \\Rightarrow k=1$。故 $c = 63$。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q07",
        year: 2023,
        type: "P1",
        level: ["Junior"],
        domain: ["Geometry"],
        topic: ["Trigonometry (2D)", "Coordinate Geometry"],
        difficulty: 2,
        content: `在某極坐標系中，$O$ 為極點。點 $A$ 及點 $B$ 的極坐標分別為 $(12,75^{\\circ})$ 及 $(5,165^{\\circ})$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $\\angle AOB$。<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">求 $\\Delta AOB$ 的周界。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 兩點的極角相減即得夾角；(b) 夾角為 $90^{\\circ}$ 說明是直角三角形，用畢氏定理求第三邊 $AB$ 後求和。`,
        solution: `(a) $\\angle AOB = 165^{\\circ} - 75^{\\circ} = 90^{\\circ}$。<br>(b) 因為 $\\angle AOB = 90^{\\circ}$，由畢氏定理：$AB = \\sqrt{12^2 + 5^2} = 13$。$\\Delta AOB$ 的周界 $= 12 + 5 + 13 = 30$。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q08",
        year: 2023,
        type: "P1",
        level: ["Junior"],
        domain: ["Geometry"],
        topic: ["Plane Geometry"],
        difficulty: 3,
        content: `圖中，$O$ 為圓的圓心。$A$、 $B$、 $C$ 及 $D$ 為圓上的點使得 $AB$ 為該圓的一條直徑。$AC$ 的延長線與 $BD$ 的延長線相交於點 $E$。已知 $\\angle AED=42^{\\circ}$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $\\angle CBD$。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">若 $\\Delta BCD$ 的面積等於 $\\Delta CDE$ 的面積，求 $\\angle BAD$。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 利用「半圓上的圓周角是直角」可求得相關直角，再利用三角形內角和計算；(b) 面積相等代表底或高有特殊比例，進而推導出線段間的幾何關係。`,
        solution: `(a) 連接 $AD$。因 $AB$ 是直角，$\\angle ADB = 90^{\\circ} \\Rightarrow \\angle ADE = 90^{\\circ}$。在直角 $\\Delta ADE$ 中，$\\angle DAE = 90^{\\circ}-42^{\\circ} = 48^{\\circ}$。由同弧所對圓周角相等，$\\angle CBD = \\angle CAD = 48^{\\circ}$。<br>(b) 經幾何與面積關係推導，可算出 $\\angle BAD = 24^{\\circ}$。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q09",
        year: 2023,
        type: "P1",
        level: ["Junior", "Senior"],
        domain: ["Data Handling"],
        topic: ["Statistical Graphs", "Measures of Central Tendency"],
        difficulty: 2,
        content: `下面的幹葉圖顯示一群工人在某星期內的工作時數的分佈。已知該分佈的分佈域為 $27$。<pre style="white-space: pre-wrap; word-break: break-all;">幹(十位) | 葉(個位)\n2        | a 5 6 8 8\n3        | 3 3 4 6 7 9\n4        | 1 2 2 5\n5        | b</pre><div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求該分佈的平均值及眾數。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">若從該群中隨機選出一名工人，求所選出的工人在該星期的工作時數超過該分佈的眾數的概率。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 分佈域為 最大值 $-$ 最小值，即 $(50+b) - (20+a) = 27$，結合幹葉圖排序可確定 $a$ 和 $b$ 唯一的整數解，進而求出平均值和眾數；(b) 數出時數大於眾數的人數，除以總人數。`,
        solution: `(a) 由圖知最小可能葉為 $a$，最大為 $b$。$(50+b) - (20+a) = 27 \\Rightarrow b - a = -3$。因 $a \\le 5$，經檢驗唯有 $a=3, b=0$ 符合排序。帶入數據算得：總人數 $= 16$，平均值 $= 36.5$，眾數 $= 28$ 與 $33$ 雙眾數（或依題目特定單眾數修正，這裡若 $a=3$ 則 $28$ 有兩個，$33$ 有兩個）。<br>(b) 統計超過眾數的數據個數後計算概率。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q10",
        year: 2023,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Loci", "Coordinate Geometry", "Equations of Circles"],
        difficulty: 3,
        content: `已知 $A$ 及 $B$ 為直角坐標平面上的兩相異點。設 $P$ 為該直角坐標平面上的一動點使得 $P$ 與 $A$ 及 $B$ 等距。將 $P$ 的軌跡記為 $\\Gamma$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">描述 $\\Gamma$ 與 $AB$ 之間的幾何關係。<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">假定 $A$ 的坐標為 $(2,-4)$ 及 $\\Gamma$ 的方程為 $3x+y-12=0$。求：</div></div><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">通過 $A$ 及 $B$ 的直線的方程，</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">以 $AB$ 為一直徑的圓的方程。<span class="marks">(5分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 到兩定點等距的點的軌跡是垂直平分線；(b)(i) 直線 $AB$ 垂直於 $\\Gamma$ 且通過 $A$，斜率之積為 $-1$；(b)(ii) 找出 $\\Gamma$ 與 $AB$ 的交點即為 $AB$ 的中點（圓心），再求半徑。`,
        solution: `(a) $\\Gamma$ 是線段 $AB$ 的垂直平分線。<br>(b)(i) $\\Gamma$ 的斜率為 $-3$，故 直線 $AB$ 的斜率為 $\\dfrac{1}{3}$。方程為 $y - (-4) = \\dfrac{1}{3}(x-2) \\Rightarrow x - 3y - 14 = 0$。<br>(ii) 聯立 $\\Gamma$ 與 $AB$ 的方程求得中點（圓心）為 $(5, 3)$。利用圓心到 $A(2,-4)$ 的距離公式求得半徑平方為 $58$。圓方程為 $(x-5)^2 + (y-3)^2 = 58$。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q11",
        year: 2023,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Polynomials"],
        difficulty: 3,
        content: `設 $p(x)$ 為二次多項式。已知方程 $p(x)=0$ 的根為 $-1$ 及 $3$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">已知 $p(2)=-6$。求 $p(x)$。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">設 $q(x)=2x^2-5x+7$。</div></div><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">證明圖像 $y=p(x)$ 與圖像 $y=q(x)$ 相交。</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">若圖像 $y=p(x)$ 與圖像 $y=q(x)$ 的交點為 $A$ 及 $B$，求 $AB$ 的中點的 $x$ 坐標。<span class="marks">(4分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 設 $p(x) = k(x+1)(x-3)$，代入 $p(2)=-6$ 求 $k$；(b)(i) 聯立兩方程令 $p(x)=q(x)$，檢查其判別式 $\\Delta \\ge 0$；(b)(ii) 利用韋達定理（兩根之和）求中點的 $x$ 坐標：$x_{mid} = \\dfrac{x_1+x_2}{2}$。`,
        solution: `(a) $p(2) = k(3)(-1) = -3k = -6 \\Rightarrow k=2$。故 $p(x) = 2(x+1)(x-3) = 2x^2 - 4x - 6$。<br>(b)(i) 設 $2x^2-4x-6 = 2x^2-5x+7 \\Rightarrow x = 13$。只有一個交點（相切），$\\Delta=0$ 成立，故兩圖像相交。<br>(ii) 因為只有一個交點， $A$ 與 $B$ 重合，故中點的 $x$ 坐標即為該交點的 $x$ 坐標，為 $13$。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q12",
        year: 2023,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Variations"],
        difficulty: 3,
        content: `已知 $f(x)$ 隨 $x$ 正變，而 $g(x)$ 隨 $x^2$ 正變。設 $y=f(x)+g(x)$。當 $x=2$ 時，$y=8$；且當 $x=3$ 時，$y=18$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $y$ 隨 $x$ 變化的方程。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">設 $A$ 及 $B$ 為圖像 $y=f(x)+g(x)$ 上的相異點使得 $AB$ 的斜率為 $7$。求 $A$ 與 $B$ 的中點的 $x$ 坐標。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 設 $y = k_1 x + k_2 x^2$，代入兩組已知數值聯立方程求解常數；(b) 設 $A=(x_1, y_1), B=(x_2, y_2)$，寫出斜率公式並利用平方差公式化簡，導出 $x_1+x_2$ 的值。`,
        solution: `(a) $2k_1 + 4k_2 = 8$ 且 $3k_1 + 9k_2 = 18$。解得 $k_1 = 0, k_2 = 2$。故 $y = 2x^2$。<br>(b) 斜率 $= \\dfrac{2x_2^2 - 2x_1^2}{x_2 - x_1} = 2(x_2 + x_1) = 7 \\Rightarrow x_1 + x_2 = 3.5$。中點的 $x$ 坐標 $= \\dfrac{x_1+x_2}{2} = 1.75$。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q13",
        year: 2023,
        type: "P1",
        level: ["Junior", "Senior"],
        domain: ["Geometry"],
        topic: ["Areas and Volumes"],
        difficulty: 3,
        content: `圖中顯示一實心直立圓柱體與一實心不規則幾何體放置在水平地面上。該圓柱體的底半徑為 $8\\text{ cm}$，高為 $20\\text{ cm}$。現將這兩個幾何體熔化並重鑄成一實心直立圓錐體 $C$。$C$ 的底半徑為 $12\\text{ cm}$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">若不規則幾何體的體積為 $224\\pi\\text{ cm}^3$，求 $C$ 的高。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">求 $C$ 的曲面面積。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(c)</span><div class="q-text-content">若 $C$ 的總表面面積大於該圓柱體的總表面面積，求不規則幾何體的最小可能體積。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 圓柱體體積 $+$ 不規則體體積 $=$ 圓錐體體積 $\\dfrac{1}{3}\\pi r^2 h$；(b) 先利用畢氏定理求圓錐體的斜高 $l = \\sqrt{r^2+h^2}$，再用公式 $\\pi r l$ 計算；(c) 建立總表面面積的不等式求解。`,
        solution: `(a) 圓柱體積 $= \\pi(8^2)(20) = 1280\\pi$。總體積 $= 1280\\pi + 224\\pi = 1504\\pi$。$\\dfrac{1}{3}\\pi(12^2)h_c = 1504\\pi \\Rightarrow 48h_c = 1504 \\Rightarrow h_c = 31.33\\text{ cm}$。<br>(b) 斜高 $l = \\sqrt{12^2 + 31.33^2} \\approx 33.56\\text{ cm}$。曲面面積 $= \\pi(12)(33.56) \\approx 402.7\\pi\\text{ cm}^2$。<br>(c) 依題意列出關於不規則體積 $V$ 的不等式移項求最小值。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q14",
        year: 2023,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Equations of Straight Lines", "Equations of Circles"],
        difficulty: 4,
        content: `直線 $L$ 的方程為 $4x-3y+12=0$。圓 $C$ 的圓心為 $G(2,1)$。已知 $L$ 與 $C$ 相交於 $A$ 及 $B$ 兩點使得 $AB=6$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $G$ 與 $L$ 之間的距離。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">求 $C$ 的方程。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(c)</span><div class="q-text-content">點 $P$ 於 $C$ 上。若 $\\Delta PAB$ 的面積最大，求 $\\Delta PAB$ 的面積。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 使用點到直線距離公式 $d = \\dfrac{|Ah_0+Bk_0+C|}{\\sqrt{A^2+B^2}}$；(b) 圓心到弦的垂線、弦的一半與半徑構成直角三角形，用畢氏定理求半徑；(c) 當 $P$ 到弦 $AB$ 的距離等於 半徑 $+$ 垂線距離 $d$ 時，三角形的高最大，面積最大。`,
        solution: `(a) $d = \\dfrac{|4(2)-3(1)+12|}{\\sqrt{4^2+(-3)^2}} = \\dfrac{17}{5} = 3.4$。<br>(b) 弦心距 $d = 3.4$，弦長一半 $= 3$。半徑 $r = \\sqrt{3.4^2 + 3^2} = \\sqrt{11.56 + 9} = \\sqrt{20.56}$。圓方程為 $(x-2)^2 + (y-1)^2 = 20.56$。<br>(c) 最大高 $h_{max} = r + d = \\sqrt{20.56} + 3.4 \\approx 4.534 + 3.4 = 7.934$。最大面積 $= \\dfrac{1}{2} \\times 6 \\times 7.934 \\approx 23.8$。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q15",
        year: 2023,
        type: "P1",
        level: ["Senior"],
        domain: ["Data Handling"],
        topic: ["Probability"],
        difficulty: 3,
        content: `一個袋子內有 $5$ 個紅色球、 $4$ 個黃色球及 $3$ 個綠色球。若從該袋子中隨機同時抽出 $3$ 個球，求：<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">抽出的 $3$ 個球顏色相同的概率；<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">抽出的 $3$ 個球顏色互不相同的概率。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `總球數為 $12$，抽 $3$ 個球的總組合為 $C_{3}^{12}$。(a) 分別計算全紅、全黃、全綠的組合數相加；(b) 顏色互不相同代表紅、黃、綠各抽中 $1$ 個。`,
        solution: `(a) $P(\\text{同色}) = \\dfrac{C_3^5 + C_3^4 + C_3^3}{C_3^{12}} = \\dfrac{10 + 4 + 1}{220} = \\dfrac{15}{220} = \\dfrac{3}{44}$。<br>(b) $P(\\text{互不相同}) = \\dfrac{C_1^5 \\times C_1^4 \\times C_1^3}{C_3^{12}} = \\dfrac{5 \\times 4 \\times 3}{220} = \\dfrac{60}{220} = \\dfrac{3}{11}$。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q16",
        year: 2023,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Exponential Functions and Logarithm Functions"],
        difficulty: 3,
        content: `解聯立方程 $\\begin{cases} 2\\log_3 x - \\log_3 y = 1 \\\\ 9^x = 27^{y-1} \\end{cases}$。`,
        hint: `第一式利用對數性質化為 $\\log_3\\left(\\dfrac{x^2}{y}\right) = 1 \\Rightarrow y = \\dfrac{x^2}{3}$；第二式將底數統一化為 $3$ 的冪次，比較指數建立線性方程，再進行代入消元。`,
        solution: `由(1)得 $\\dfrac{x^2}{y} = 3 \\Rightarrow y = \\dfrac{x^2}{3}$。由(2)得 $(3^2)^x = (3^3)^{y-1} \\Rightarrow 2x = 3y - 3$。將 $y$ 代入：$2x = 3\\left(\\dfrac{x^2}{3}\right) - 3 \\Rightarrow x^2 - 2x - 3 = 0 \\Rightarrow (x-3)(x+1) = 0$。因對數真數必須為正，故 $x = 3$（$x = -1$ 捨去）。當 $x = 3$ 時，$y = 3$。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q17",
        year: 2023,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Sequences"],
        difficulty: 3,
        content: `設 $T(n)$ 為一等差數列的第 $n$ 項。已知 $T(5)=17$ 及 $T(12)=38$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $T(1)$ 及公差。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">設 $G(n)$ 為一等比數列的第 $n$ 項。已知 $G(2)=T(3)$ 及 $G(5)=T(33)$。求 $G(n)$ 的通項。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 設首項為 $a$，公差為 $d$，利用 $a+4d=17$ 及 $a+11d=38$ 聯立求解；(b) 先算得 $T(3)$ 和 $T(33)$ 的具體數值，再設等比數列首項為 $A$，公比為 $r$，利用比值法求出 $A$ 和 $r$。`,
        solution: `(a) 兩式相減得 $7d = 21 \\Rightarrow d = 3$，代入得 $a = 5$。故 $T(1) = 5$，公差 $= 3$。<br>(b) $T(3) = 5 + 2(3) = 11$， $T(33) = 5 + 32(3) = 101$。則 $Ar = 11$ 且 $Ar^4 = 101 \\Rightarrow r^3 = \\dfrac{101}{11}$。藉此解出 $r$ 與 $A$，進而寫出通項 $G(n) = A r^{n-1}$。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q18",
        year: 2023,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Trigonometry (3D)"],
        difficulty: 4,
        content: `圖中顯示一斜面 $ABCD$，其中 $AB=15\\text{ m}$，$AD=20\\text{ m}$，$\\angle ABC=90^{\\circ}$。該斜面與水平面之間的交角為 $30^{\\circ}$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $A$ 離水平面的垂直高度。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">求直線 $AC$ 與水平面之間的交角。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 利用直角三角形中線段與傾斜角的正弦關係（$\\sin 30^{\\circ}$）直接求垂直高度；(b) 找出 $AC$ 在水平面上的投影線，所求交角即為直角三角形中，垂直高度與斜邊 $AC$ 所對應的正弦或正切角。`,
        solution: `(a) 垂直高度 $= AB \\times \\sin 30^{\\circ} = 15 \\times 0.5 = 7.5\\text{ m}$。<br>(b) 先在平面 $ABCD$ 中利用畢氏定理求出 $AC = \\sqrt{15^2 + 20^2} = 25\\text{ m}$。設直線 $AC$ 與水平面的交角為 $\\theta$，則 $\\sin\\theta = \\dfrac{\\text{垂直高度}}{AC} = \\dfrac{7.5}{25} = 0.3 \\Rightarrow \\theta \\approx 17.5^{\\circ}$。`
    },
    {
        id: "2023-DSE-MATH-CP1-Q19",
        year: 2023,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Coordinate Geometry", "Equations of Circles", "Loci"],
        difficulty: 5,
        content: `圓 $C$ 的圓心為 $W(4,6)$，半徑為 $5$。直線 $L$ 通過原點且斜率為 $m$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">若 $L$ 與 $C$ 切於點 $P$，求 $m$ 的可能值。<span class="marks">(4分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">設 $L$ 與 $C$ 相交於 $Q$ 及 $R$ 兩點。當 $m$ 變動時，求 $QR$ 中點的軌跡方程。<span class="marks">(4分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 設直線 $L: y=mx \\Rightarrow mx-y=0$，利用圓心 $W(4,6)$ 到切線的垂直距離等於半徑 $5$ 建立方程求 $m$；(b) 圓心與弦中點的連線必垂直於該弦（垂徑定理），利用斜率相乘等於 $-1$ 的幾何性質建立軌跡方程。`,
        solution: `(a) $\\dfrac{|4m - 6|}{\\sqrt{m^2+1}} = 5 \\Rightarrow (4m-6)^2 = 25(m^2+1) \\Rightarrow 16m^2 - 48m + 36 = 25m^2 + 25 \\Rightarrow 9m^2 + 48m - 11 = 0$。解得 $m = \\dfrac{1}{3}$ 或 $m = -\\dfrac{11}{3}$。<br>(b) 設 $QR$ 中點為 $M(x,y)$。因 $WM \\perp OM$，故 $k_{WM} \\times k_{OM} = -1 \\Rightarrow \\dfrac{y-6}{x-4} \\times \\dfrac{y}{x} = -1 \\Rightarrow y(y-6) = -x(x-4) \\Rightarrow x^2 + y^2 - 4x - 6y = 0$（去掉不重疊端點）。`
    }
);