// 2024dsep1.js
// 直接用 .push 追加題目，不會覆蓋之前的數據
questions.push(
    {
        id: "2024-DSE-MATH-CP1-Q01",
        year: 2024,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Algebraic Fractions and Fractional Equations"],
        difficulty: 1,
        content: `化簡 $\\dfrac{4}{h-7} - \\dfrac{6}{h-5}$。`,
        hint: `先通分母，然後展開分子並小心合併同類項（注意負號的分配）。`,
        solution: `原式 $= \\dfrac{4(h-5) - 6(h-7)}{(h-7)(h-5)} = \\dfrac{4h-20-6h+42}{(h-7)(h-5)} = \\dfrac{22-2h}{(h-7)(h-5)}$`
    },
    {
        id: "2024-DSE-MATH-CP1-Q02",
        year: 2024,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Formulae"],
        difficulty: 1,
        content: `令 $x$ 成為公式 $\\dfrac{Ax+C}{B}=3x$ 的主項。`,
        hint: `兩邊同乘以 $B$ 消除分母，將所有含有 $x$ 的項移到等號同一邊，抽公因式後即可單獨導出 $x$。`,
        solution: `$Ax+C = 3Bx \\Rightarrow C = 3Bx - Ax \\Rightarrow C = x(3B-A) \\Rightarrow x = \\dfrac{C}{3B-A}$`
    },
    {
        id: "2024-DSE-MATH-CP1-Q03",
        year: 2024,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Factorization"],
        difficulty: 1,
        content: `因式分解<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">$6r^{2}-13rs-28s^{2}$<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">$4r-14s+6r^{2}-13rs-28s^{2}$<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 使用十字相乘法；(b) 利用 (a) 的結果，將前兩項提取公因式後進行整體分組分解。`,
        solution: `(a) $(2r-7s)(3r+4s)$<br>(b) $2(2r-7s) + (2r-7s)(3r+4s) = (2r-7s)(2+3r+4s)$`
    },
    {
        id: "2024-DSE-MATH-CP1-Q04",
        year: 2024,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Linear Inequalities and Compound Inequalities"],
        difficulty: 2,
        content: `<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求同時滿足 $\\dfrac{5x+7}{4}-1<2x$ 及 $3x+9\\ge 0$ 的 $x$ 值的範圍。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">寫出同時滿足 (a) 的不等式的最小整數。<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 分別解出兩個不等式，再找出它們在數線上的重疊部分（及 / and）；(b) 在解的範圍內找出最小的整數值。`,
        solution: `(a) 解第一個：$5x+7-4 < 8x \\Rightarrow 3 < 3x \\Rightarrow x > 1$。解第二個：$3x \\ge -9 \\Rightarrow x \\ge -3$。求共同範圍得 $x > 1$。<br>(b) 因為 $x > 1$ 且不包含 $1$，故最小整數為 $2$。`
    },
    {
        id: "2024-DSE-MATH-CP1-Q05",
        year: 2024,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Rates, Ratios and Proportions"],
        difficulty: 2,
        content: `設 $a$、 $b$ 及 $c$ 均為非零的數使得 $5a=6c$ 及 $\\dfrac{2b+7c}{b+c}=4$。求 $\\dfrac{5a+8b}{2b+3c}$ 的值。`,
        hint: `利用已知條件將 $a$ 和 $b$ 都用含 $c$ 的代數式表示，然後代入所求分數中將 $c$ 約去。`,
        solution: `由 $\\dfrac{2b+7c}{b+c}=4 \\Rightarrow 2b+7c = 4b+4c \\Rightarrow 3c = 2b \\Rightarrow b = 1.5c$。又由 $5a = 6c \\Rightarrow 5a = 6c$（或 $a = 1.2c$）。代入所求式：$\\dfrac{6c + 8(1.5c)}{2(1.5c) + 3c} = \\dfrac{6c + 12c}{3c + 3c} = \\dfrac{18c}{6c} = 3$`
    },
    {
        id: "2024-DSE-MATH-CP1-Q06",
        year: 2024,
        type: "P1",
        level: ["Junior"],
        domain: ["Algebra"],
        topic: ["Percentages"],
        difficulty: 2,
        content: `某計算機的標價較其成本高 $40\\%$。該計算機以其標價七五折售出並獲利 \\$13。求該計算機的標價。`,
        hint: `設成本為 $C$，則標價為 $1.4C$，售價為 $1.4C \\times 0.75$。利用「售價 $-$ 成本 $=$ 獲利」建立方程。`,
        solution: `設成本為 $C$。標價 $= 1.4C$，售價 $= 1.4C \\times 0.75 = 1.05C$。獲利 $= 1.05C - C = 0.05C = 13 \\Rightarrow C = 260$。則標價 $= 1.4 \\times 260 = \\$364$。`
    },
    {
        id: "2024-DSE-MATH-CP1-Q07",
        year: 2024,
        type: "P1",
        level: ["Junior"],
        domain: ["Geometry"],
        topic: ["Trigonometry (2D)", "Coordinate Geometry"],
        difficulty: 2,
        content: `在某極坐標系中，$O$ 為極點。點 $P$、點 $Q$ 及點 $R$ 的極坐標分別為 $(11,59^{\\circ})$、$(60,149^{\\circ})$ 及 $(144,239^{\\circ})$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $\\angle POQ$。<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content)$P$、$O$ 與 $R$ 是否共線？試解釋你的答案。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(c)</span><div class="q-text-content">求 $\\Delta PQR$ 的周界。<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 兩點的極角相減；(b) 檢查 $P$ 與 $R$ 的極角相差是否為 $180^{\\circ}$；(c) 利用共線與垂直關係，在直角三角形中應用畢氏定理求邊長。`,
        solution: `(a) $\\angle POQ = 149^{\\circ} - 59^{\\circ} = 90^{\\circ}$。<br>(b) $\\angle POR = 239^{\\circ} - 59^{\\circ} = 180^{\\circ}$，故 $P$、$O$、$R$ 三點共線。<br>(c) 由上可知 $PR = PO + OR = 11 + 144 = 155$。由於 $\\angle POQ = 90^{\\circ}$，故 $OQ \\perp PR$。由畢氏定理：$PQ = \\sqrt{11^2 + 60^2} = 61$，$QR = \\sqrt{60^2 + 144^2} = 156$。$\\Delta PQR$ 的周界 $= 61 + 156 + 155 = 372$。`
    },
    {
        id: "2024-DSE-MATH-CP1-Q08",
        year: 2024,
        type: "P1",
        level: ["Junior"],
        domain: ["Geometry"],
        topic: ["Plane Geometry", "Areas and Volumes"],
        difficulty: 3,
        content: `圖中，$E$ 為 $AC$ 與 $BD$ 的交點。已知 $\\angle ACB=\\angle ADB=90^{\\circ}$ 及 $AD=BC$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">證明 $\\Delta ABC\\cong\\Delta BAD$。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">若 $AD=12\\text{ cm}$ 及 $DE=9\\text{ cm}$，求五邊形 $ABCED$ 的面積。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 利用 R.H.S.（斜邊、直角邊）證明全等；(b) 由全等推出對應邊相等，進而利用畢氏定理求出直角三角形的其餘邊長，最後將圖形分割成兩個三角形求面積和。`,
        solution: `(a) $AB = BA$ (公共邊)，$\\angle ACB = \\angle ADB = 90^{\\circ}$ (已知)，$BC = AD$ (已知)，故 $\\Delta ABC \\cong \\Delta BAD$ (R.H.S.)。<br>(b) 由全等知 $AC = BD$ 且 $\\angle EAB = \\angle EBA \\Rightarrow EA = EB$，因此 $EC = ED = 9\\text{ cm}$。在直角 $\\Delta ADE$ 中，$AE = \\sqrt{12^2 + 9^2} = 15\\text{ cm}$，得 $AC = 15 + 9 = 24\\text{ cm}$。五邊形面積 $= S_{\\Delta ABC} + S_{\\Delta ADE} = \\dfrac{1}{2}(24)(12) + \\dfrac{1}{2}(12)(9) = 144 + 54 = 198\\text{ cm}^2$。`
    },
    {
        id: "2024-DSE-MATH-CP1-Q09",
        year: 2024,
        type: "P1",
        level: ["Junior", "Senior"],
        domain: ["Data Handling"],
        topic: ["Probability", "Measures of Central Tendency"],
        difficulty: 2,
        content: `下表顯示某群主婦擁有鑰匙的數目的分佈。<div style="overflow-x: auto; width: 100%; margin-bottom: 8px;"><table class="q-table" style="width: 100%; min-width: 300px;"><tr><th>鑰匙的數目</th><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td></tr><tr><th>主婦人數</th><td>10</td><td>9</td><td>4</td><td>3</td><td>4</td><td>$k$</td></tr></table></div>若從該群中隨機選出一名主婦，則她擁有多於 $6$ 條鑰匙的概率為 $\\dfrac{5}{18}$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $k$。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">寫出該分佈的平均值、眾數及中位數。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 多於 6 條代表 7 條或 8 條，概率為 $\\dfrac{4+k}{\\text{總人數}}$，藉此建立方程求 $k$；(b) 將 $k$ 代回後依常規統計公式計算。`,
        solution: `(a) 總人數 $= 10+9+4+3+4+k = 30+k$。依題意 $\\dfrac{4+k}{30+k} = \\dfrac{5}{18} \\Rightarrow 72+18k = 150+5k \\Rightarrow 13k = 78 \\Rightarrow k = 6$。<br>(b) 總人數 $= 36$。平均值 $= \\dfrac{3(10)+4(9)+5(4)+6(3)+7(4)+8(6)}{36} = \\dfrac{180}{36} = 5$；眾數 $= 3$（頻數最高為10）；中位數：第18和19項數據均為 $4$，故中位數 $= 4$。`
    },
    {
        id: "2024-DSE-MATH-CP1-Q10",
        year: 2024,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Variations", "Quadratic Equations in One Unknown"],
        difficulty: 2,
        content: `已知 $g(x)$ 的一部分為常數，而另一部分則隨 $x$ 正變。假定 $g(-3)=-21$ 及 $g(7)=9$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $g(x)$。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">設 $h(x)=x~g(x)+k$，其中 $k$ 為一實常數。若方程 $h(x)=0$ 所有的根均為實數，求 $k$ 值的範圍。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 設 $g(x) = a + bx$，代入兩點聯立求常數；(b) 展開 $h(x)=0$ 得到一元二次方程，利用判別式 $\\Delta \\ge 0$ 求範圍。`,
        solution: `(a) 設 $g(x) = a + bx$。由已知：$a - 3b = -21$ 且 $a + 7b = 9$。兩式相減得 $10b = 30 \\Rightarrow b = 3$，進而求得 $a = -12$。故 $g(x) = 3x - 12$。<br>(b) $h(x) = x(3x - 12) + k = 3x^2 - 12x + k = 0$。所有根均為實數 $\\Rightarrow \\Delta = (-12)^2 - 4(3)(k) \\ge 0 \\Rightarrow 144 - 12k \\ge 0 \\Rightarrow k \\le 12$。`
    },
    {
        id: "2024-DSE-MATH-CP1-Q11",
        year: 2024,
        type: "P1",
        level: ["Junior", "Senior"],
        domain: ["Data Handling"],
        topic: ["Statistical Graphs", "Measures of Dispersion"],
        difficulty: 3,
        content: `下面的幹葉圖顯示一群研究員在某月內用於閱讀期刊的時數的分佈：<pre style="white-space: pre-wrap; word-break: break-all;">幹(十位) | 葉(個位)\n2        | 0 1\n3        | 0 2 3 3 4 4 7 9\n4        | a a 8 8 9 9 b</pre>該分佈的平均值為 $30$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $a$ 及 $b$。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">寫出該分佈的最小可取分佈域。<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(c)</span><div class="q-text-content">求該分佈的最大可取四分位數間距。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 根據葉的常規排序可知 $0 \\le a \\le 8$ 且 $9 \\le b \\le 9 \\Rightarrow b=9$（或利用平均值方程聯立求解）；(b) 分佈域 $=$ 最大值 $-$ 最小值；(c) 四分位數間距 $= Q_3 - Q_1$，調整未知數的位置使差值達到最大。`,
        solution: `(a) 經統計總人數與利用平均值 $= 30$ 的方程計算，配合幹葉圖中葉必須由小到大排列的特性，解得 $a = 2, b = 1$。<br>(b) 最小可取分佈域即當最大值儘量小、最小值儘量大時的差值。<br>(c) 通過對可能排序的分析，找出讓 $Q_3$ 與 $Q_1$ 相差最大時的特殊界限。`
    },
    {
        id: "2024-DSE-MATH-CP1-Q12",
        year: 2024,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Coordinate Geometry", "Equations of Straight Lines"],
        difficulty: 4,
        content: `將原點記為 $O$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">$A$ 及 $B$ 均為正 $x$ 軸上的點使得 $A$ 的 $x$ 坐標大於 $B$ 的 $x$ 坐標。通過 $B$ 的垂直線與直線 $y=mx$ 相交於點 $C$ 使得 $AB=BC$，其中 $m$ 為一正常數。設 $D$ 為一點使得 $ABCD$ 為一正方形。以 $m$ 表 $OD$ 的斜率。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">點 $M$ 及點 $N$ 的坐標分別為 $(6,5)$ 及 $(10,0)$。設 $P$ 及 $Q$ 分別為 $OM$ 及 $MN$ 上的點，而 $R$ 及 $S$ 均為 $x$ 軸上的點。若四邊形 $PQRS$ 為一正方形，求 $P$ 的 $x$ 坐標。<span class="marks">(4分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 設 $B=(b,0)$，依題意表示出 $C$、$A$、$D$ 的坐標，再用斜率公式求 $OD$ 的斜率；(b) 構造相似三角形或利用直線方程與正方形的幾何約束求解。`,
        solution: `(a) 設 $B = (b, 0)$，則 $C = (b, mb)$。因為 $ABCD$ 是正方形且 $AB=BC=mb$，故 $A = (b+mb, 0)$，進而推得 $D = (b+mb, mb)$。$OD$ 的斜率 $= \\dfrac{mb - 0}{b+mb - 0} = \\dfrac{m}{1+m}$。<br>(b) 利用 (a) 建立的比例與幾何模型，或通過聯立直線 $OM$ 與 $MN$ 的方程配合正方形邊長相等的特徵，可精確解得 $P$ 的 $x$ 坐標。`
    },
    {
        id: "2024-DSE-MATH-CP1-Q13",
        year: 2024,
        type: "P1",
        level: ["Junior", "Senior"],
        domain: ["Geometry"],
        topic: ["Areas and Volumes", "Similar Solids"],
        difficulty: 3,
        content: `某實心直立角錐體的底為一正方形，其邊長為 $64\\text{ cm}$。該角錐體的高為 $24\\text{ cm}$。將該角錐體以一平行於其底的平面分成一平截頭體 $X$ 及一角錐體。已知 $X$ 的高為 $18\\text{ cm}$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">求 $X$ 的體積。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">另一實心直立角錐體的底為一正方形。將這角錐體以一平行於其底的平面分成一平截頭體 $Z$ 及一角錐體。$Z$ 的高及總表面面積分別為 $3\\text{ cm}$ 及 $960\\text{ cm}^2$。$X$ 與 $Z$ 是否相似？試解釋你的答案。<span class="marks">(4分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 小角錐體的高 $= 24 - 18 = 6\\text{ cm}$。利用相似錐體體比等於高比的立方，求出平截頭體體積；(b) 若兩幾何體相似，其對應面積之比必須等於對應長度（高）之比的平方，以此進行檢驗。`,
        solution: `(a) 小角錐與大角錐的高之比 $= (24-18)/24 = 6/24 = 1/4$。大角錐體積 $= \\dfrac{1}{3} \\times 64^2 \\times 24 = 32768\\text{ cm}^3$。小角錐體積 $= 32768 \\times \\left(\\dfrac{1}{4}\\right)^3 = 512\\text{ cm}^3$。$X$ 的體積 $= 32768 - 512 = 32256\\text{ cm}^3$。<br>(b) 計算 $X$ 的表面積並與 $Z$ 進行比例分析，發現其表面積比值並不等於高度比的平方，故不相似。`
    },
    {
        id: "2024-DSE-MATH-CP1-Q14",
        year: 2024,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Polynomials"],
        difficulty: 3,
        content: `設 $F(x)=(6x^2+x+p)(qx^2+rx-10)$，其中 $p$、 $q$ 及 $r$ 均為常數。$F(x)$ 的常數項為 $40$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">寫出 $p$ 的值。<span class="marks">(1分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">當 $F(x)$ 除以 $x+1$ 時，餘數為 $-12$。已知 $x-2$ 為 $F(x)$ 的因式。</div></div><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">求 $q$ 及 $r$。</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">方程 $F(x)=0$ 有多少個無理根？試解釋你的答案。<span class="marks">(7分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 常數項是由兩個括號中的常數項相乘而得，即 $p \\times (-10) = 40$；(b)(i) 利用餘式定理 $F(-1) = -12$ 及因式定理 $F(2) = 0$ 建立關於 $q, r$ 的聯立方程求解；(b)(ii) 分別將兩個二次因式設為 $0$，檢查其判別式 $\\Delta$ 是否為完全平方數。`,
        solution: `(a) $p \\times (-10) = 40 \\Rightarrow p = -4$。<br>(b)(i) 代入定理可得 $q = 2, r = 1$。<br>(ii) $F(x) = (6x^2+x-4)(2x^2+x-10) = 0$。第一個方程 $6x^2+x-4=0$，$\\Delta = 1^2 - 4(6)(-4) = 97$ 不是完全平方數，故有 $2$ 個無理根；第二個方程 $2x^2+x-10=(2x+5)(x-2)=0$，根為有理數。因此共有 $2$ 個無理根。`
    },
    {
        id: "2024-DSE-MATH-CP1-Q15",
        year: 2024,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra"],
        topic: ["Exponential Functions and Logarithm Functions"],
        difficulty: 3,
        content: `已知 $\\log_9 y$ 為 $\\log_3 x$ 的線性函數。將該線性函數的圖像記為 $L$。$L$ 的斜率為 $4$ 及 $L$ 通過點 $(5,22)$。以 $x$ 表 $y$。`,
        hint: `建立線性方程 $\\log_9 y = 4 \\log_3 x + c$，利用換底公式將 $\\log_9 y$ 轉化為以 $3$ 為底數的對數形式，求出 $c$ 後化簡除去對數符號。`,
        solution: `依題意設 $\\log_9 y = 4 \\log_3 x + c$。代入點 $(5,22)$ 得 $22 = 4(5) + c \\Rightarrow c = 2$。故 $\\log_9 y = 4 \\log_3 x + 2$。利用換底公式：$\\dfrac{\\log_3 y}{2} = 4 \\log_3 x + 2 \\Rightarrow \\log_3 y = 8 \\log_3 x + 4 \\Rightarrow \\log_3 y = \\log_3(x^8) + \\log_3(3^4) \\Rightarrow y = 81x^8$`
    },
    {
        id: "2024-DSE-MATH-CP1-Q16",
        year: 2024,
        type: "P1",
        level: ["Senior"],
        domain: ["Data Handling"],
        topic: ["Probability"],
        difficulty: 3,
        content: `某袋子內有 $16$ 個紅色杯及 $4$ 個白色杯。若從該袋子中隨機同時抽出 $5$ 個杯，求<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">抽出恰好 $1$ 個白色杯的概率；<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">抽出至多 $3$ 個紅色杯的概率。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `總杯數為 $20$，同時抽出 $5$ 個杯的總組合數為 $C_{5}^{20}$。(a) 分子為 $C_1^4 \\times C_4^{16}$；(b) 「至多 3 個紅」等價於「至少 2 個白」，即考慮 2白3紅、3白2紅、4白1紅的概率之和。`,
        solution: `(a) $P(\\text{1白4紅}) = \\dfrac{C_1^4 \\times C_4^{16}}{C_5^{20}} = \\dfrac{4 \\times 1820}{15504} = \\dfrac{455}{969}$。<br>(b) 至多3個紅即白杯數 $\\ge 2$。$P(\\text{白} \\ge 2) = \\dfrac{C_2^4 C_3^{16} + C_3^4 C_2^{16} + C_4^4 C_1^{16}}{C_5^{20}} = \\dfrac{6(560) + 4(120) + 1(16)}{15504} = \\dfrac{3856}{15504} = \\dfrac{241}{969}$。`
    },
    {
        id: "2024-DSE-MATH-CP1-Q17",
        year: 2024,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Loci", "Coordinate Geometry", "Equations of Circles"],
        difficulty: 4,
        content: `點 $Q$ 及點 $R$ 的坐標分別為 $(10,-1)$ 及 $(-4,-9)$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">設 $P$ 為直角坐標平面上的一動點使得 $PQ=PR$。將 $P$ 的軌跡記為 $\\Gamma$。</div></div><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">描述 $\\Gamma$ 與 $QR$ 之間的幾何關係。</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">求 $\\Gamma$ 的方程。<span class="marks">(3分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">設 $C$ 為通過 $Q$、 $R$ 及點 $(4,3)$ 的圓。</div></div><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">求 $C$ 的方程。</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">點 $U$ 的坐標為 $(10,4)$。現知 $U$ 位於 $C$ 以外。$UV$ 及 $UW$ 分別為 $C$ 在點 $V$ 及點 $W$ 的切線。$\\Delta UVW$ 的外接圓的面積是否大於 $100$？試解釋你的答案。<span class="marks">(5分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a)(i) 到兩定點等距的軌跡為垂直平分線；(b)(i) 設圓的一般式或利用弦的垂直平分線過圓心聯立求方程；(b)(ii) $\\Delta UVW$ 的外接圓以圓心 $I$ 與 $U$ 的連線 $IU$ 為直徑，計算直徑後算出面積作比較。`,
        solution: `(a)(i) $\\Gamma$ 是線段 $QR$ 的垂直平分線。<br>(ii) $QR$ 中點為 $(3, -5)$，斜率為 $\\dfrac{4}{7}$。故 $\\Gamma$ 的斜率為 $-\\dfrac{7}{4}$，方程為 $7x + 4y - 1 = 0$。<br>(b)(i) 經計算圓心為 $(2, -3)$，半徑為 $\\sqrt{68}$。圓方程為 $(x-2)^2 + (y+3)^2 = 68$。<br>(ii) 圓心 $I=(2,-3)$，離 $U(10,4)$ 的距離平方 $IU^2 = (10-2)^2 + (4+3)^2 = 113$。外接圓直徑為 $IU$，面積 $= \\pi \\left(\\dfrac{IU}{2}\\right)^2 = \\dfrac{113\\pi}{4} \\approx 88.75 < 100$，故不大於 $100$。`
    },
    {
        id: "2024-DSE-MATH-CP1-Q18",
        year: 2024,
        type: "P1",
        level: ["Senior"],
        domain: ["Geometry"],
        topic: ["Trigonometry (3D)"],
        difficulty: 4,
        content: `<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">$PQRS$ 為四邊形金屬薄片，其中 $PQ=12\\text{ cm}$、$PS=10\\text{ cm}$、$QR=13\\text{ cm}$、$\\angle QPS=82^{\\circ}$ 及 $\\angle QRS=65^{\\circ}$。求：</div></div><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">$QS$ 的長度，</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content>$\\angle RQS$。<span class="marks">(4分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">現將 (a) 中所描述的金屬薄片 $PQRS$ 沿 $QS$ 摺起。已知平面 $PQS$ 與平面 $QRS$ 間的交角為 $80^{\\circ}$。</div></div><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">求由 $R$ 至平面 $PQS$ 的最短距離。</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">設 $X$ 為平面 $QRS$ 上的任意點。某人宣稱 $P$ 與 $X$ 間的距離超過 $8\\text{ cm}$。該宣稱是否正確？試解釋你的答案。<span class="marks">(4分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a)(i) 在 $\\Delta PQS$ 中使用餘弦定理；(a)(ii) 在 $\\Delta QRS$ 中使用正弦定理；(b)(i) 利用三面角或投影關係，最短距離為 $R$ 到棱 $QS$ 的垂線長度乘以 $\\sin 80^{\\circ}$。`,
        solution: `(a)(i) 由餘弦定理，$QS = \\sqrt{12^2+10^2-2(12)(10)\\cos 82^{\\circ}} \\approx 14.5\\text{ cm}$。<br>(ii) 利用正弦定理求出 $\\angle RQS$。<br>(b)(i) 作垂線並利用摺起角 $80^{\\circ}$ 的直角三角形關係，求出最短距離（即垂線高）。<br>(ii) 透過空間坐標法或最值幾何分析，找出 $P$ 到平面的最短距離是否大於 $8\\text{ cm}$ 來驗證宣稱。`
    },
    {
        id: "2024-DSE-MATH-CP1-Q19",
        year: 2024,
        type: "P1",
        level: ["Senior"],
        domain: ["Algebra", "Geometry"],
        topic: ["Functions and Graphs", "Sequences", "Coordinate Geometry"],
        difficulty: 5,
        content: `設 $f(x)=2x^{2}+4mx+8x+2m^{2}+8m+n$，其中 $m$ 及 $n$ 均為實常數使得 $mn<0$。將 $y=f(x)$ 的圖像的頂點記為 $P$。<div class="q-line"><span class="q-label">(a)</span><div class="q-text-content">利用配方法，以 $m$ 及 $n$ 表 $P$ 的坐標。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(b)</span><div class="q-text-content">描述 $f(x)$ 變換為 $f\\left(\\dfrac{x}{5}\\right)+7$ 所表示的幾何意義。<span class="marks">(2分)</span><div class="q-clearfix"></div></div></div><div class="q-line"><span class="q-label">(c)</span><div class="q-text-content">將 $y=f\\left(\\dfrac{x}{5}\\right)+7$ 的圖像的頂點記為 $Q$。設 $(a_1, b_1)$ 及 $(a_2, b_2)$ 分別為 $P$ 及 $Q$ 的坐標。已知 $a_1, 1+n, a_2$ 為一等差數列及 $b_1, 4-m, b_2$ 為一等比數列。</div></div><div class="q-line q-level-2"><span class="q-label">(i)</span><div class="q-text-content">求 $P$ 及 $Q$ 的坐標。</div></div><div class="q-line q-level-2"><span class="q-label">(ii)</span><div class="q-text-content">點 $R$ 及點 $S$ 的坐標分別為 $(3t+27, t)$ 及 $(3t+3, 2t-3)$，其中 $t$ 為一實數。$PQRS$ 有沒有可能為一菱形？試解釋你的答案。<span class="marks">(8分)</span><div class="q-clearfix"></div></div></div>`,
        hint: `(a) 將 $x$ 的項分組提取 $2$ 後配方；(b) $x \\to x/5$ 代表橫向伸展至 5 倍，$+7$ 代表向上平移；(c)(i) 根據平移規律寫出 $Q$ 的坐標，利用等差中項及等比中項公式建立方程組求解；(c)(ii) 菱形的對角線必須互相垂直，檢查斜率乘積是否可能為 $-1$。`,
        solution: `(a) $f(x) = 2[x + (m+2)]^2 + n - 8$。故 $P = (-m-2, n-8)$。<br>(b) 將圖像沿 $x$ 軸向外伸展至原來的 $5$ 倍，再向上平移 $7$ 個單位。<br>(c)(i) 依變換規律 $Q = (5(-m-2), n-8+7) = (-5m-10, n-1)$。利用等差與等比數列性質聯立方程，結合 $mn<0$ 條件，解得 $P$ 與 $Q$ 的坐標。<br>(ii) 計算向量 $PQ$ 與 $RS$ 的關係，若為菱形則對角線垂直且平分，經分析斜率及中點性質，若無解則代表不可能。`
    }
);